const {chromium}=require('playwright');const path=require('path');
(async()=>{const b=await chromium.launch();const pg=await b.newPage({viewport:{width:1280,height:800}});const errs=[];
 pg.on('console',m=>{if(m.type()==='error'&&!/Failed to load resource/.test(m.text()))errs.push(m.text())});pg.on('pageerror',e=>errs.push('PAGEERR '+e.message));
 await pg.route(/fonts\.g/,r=>r.abort());await pg.goto('file://'+path.resolve('dist/index.html')+'#notour');await pg.waitForTimeout(300);pg.setDefaultTimeout(5000);
 const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)process.exitCode=1};const ev=(f,a)=>pg.evaluate(f,a);
 await ev(()=>{GB.reset('owner');GB.root('settings');GB.go('menuList')});await pg.waitForTimeout(50);
 await pg.locator('#adddish').click();await pg.locator('#savedish').click();await pg.waitForTimeout(50);
 ok(await pg.locator('.errs').count()===1,'Saving an empty dish shows what is missing');
 await pg.fill('#md-name','Iced Lemon Tea');await pg.selectOption('#md-cat','__new');await pg.fill('#md-newcat','Specials');await pg.fill('#md-price','6.50');
 await pg.selectOption('#md-add','tea');await pg.getByRole('button',{name:'Add to recipe'}).click();await pg.fill('#md-q0','0.005');
 await pg.selectOption('#md-add','lemon');await pg.getByRole('button',{name:'Add to recipe'}).click();await pg.fill('#md-q1','0.5');
 await pg.locator('.chip',{hasText:'Sugar'}).click();await pg.locator('#savedish').click();await pg.waitForTimeout(50);
 const d=await ev(()=>GB.state().menu.find(m=>m.name==='Iced Lemon Tea'));
 ok(d&&d.price===650&&d.cat==='Specials'&&d.recipe.length===2&&d.recipe[1][1]===0.5&&d.mods.join()==='sweet','New dish saved with price, new group, recipe and options: '+JSON.stringify(d));
 const lem=await ev(()=>GB.fn.onHand('lemon'));
 await ev(()=>{GB.state().role='cashier';GB.root('pos')});await pg.waitForTimeout(50);
 ok(await pg.locator('.tab',{hasText:'Specials'}).count()===1,'The new group shows as a tab on the till');
 await pg.locator('.tab',{hasText:'Specials'}).click();await pg.locator('.mi',{hasText:'Iced Lemon Tea'}).click();await pg.getByRole('button',{name:'Add to bill'}).click();
 await pg.locator('.chip',{hasText:'Takeaway'}).click();await pg.locator('#paybtn').click();await pg.locator('.chip',{hasText:'Exact'}).click();await pg.locator('#paidbtn').click();await pg.waitForTimeout(50);
 ok(Math.abs(lem-(await ev(()=>GB.fn.onHand('lemon')))-0.5)<0.001,'Selling the new dish took 0.5 lemon off the stock');
 await ev(d=>{GB.state().role='owner';GB.root('settings');GB.go('menuList');GB.go('menuItem',{id:d.id})},d);await pg.waitForTimeout(50);
 await pg.fill('#md-price','7');await pg.locator('.btn.red',{hasText:'Remove'}).first().click();await pg.locator('#savedish').click();await pg.waitForTimeout(50);
 const d2=await ev(()=>GB.state().menu.find(m=>m.name==='Iced Lemon Tea'));ok(d2.price===700&&d2.recipe.length===1,'Changing the price and removing an ingredient is saved');
 await pg.locator('tr.click',{hasText:'Iced Lemon Tea'}).click();await pg.locator('#deldish').click();await pg.getByRole('button',{name:'Yes, delete this dish'}).click();await pg.waitForTimeout(50);
 ok(!(await ev(()=>GB.state().menu.some(m=>m.name==='Iced Lemon Tea')))&&(await ev(()=>GB.info().screen))==='menuList','Deleting removes the dish and returns to the menu list');
 await pg.locator('#toast button').click();await pg.waitForTimeout(50);ok(await ev(()=>GB.state().menu.some(m=>m.name==='Iced Lemon Tea')),'Undo brings the deleted dish back');
 await ev(()=>{GB.go('menuItem',{id:'103'})});await pg.waitForTimeout(50);await pg.locator('#deldish').click();await pg.getByRole('button',{name:'Yes, delete this dish'}).click();await pg.waitForTimeout(50);
 await ev(()=>{GB.root('pos')});await pg.waitForTimeout(50);ok(await pg.locator('.mi',{hasText:/^.*Latte.*Code 103/}).count()===0,'A deleted starter dish (Latte) is gone from the till');
 ok(errs.length===0,'No console errors '+errs.join('|'));await b.close()})().catch(e=>{console.log('CRASH',e.message.split('\n').slice(0,5).join(' '));process.exit(1)});
