/* ---------- E-invoices (simulation of LHDN MyInvois) ---------- */
const IST={Draft:['Draft',''],Submitted:['Submitted','info'],Valid:['Valid','ok'],Invalid:['Invalid','bad'],Cancelled:['Cancelled','bad']};
const ISTX={Draft:'Not sent yet. Finish the steps and press Submit.',Submitted:'Sent and waiting for LHDN to check it. This normally takes a few seconds.',Valid:'LHDN checked it and accepted it. You can give it to the buyer.',Invalid:'LHDN rejected it. Fix what is wrong and send it again.',Cancelled:'This e-invoice was cancelled and no longer counts.'};
const invBy=id=>S.invoices.find(i=>i.id===id);
const invKind=i=>i.type==='02'?'Credit note':i.kind==='consolidated'?'Combined (walk-in sales)':'E-invoice';
const hoursLeft=inv=>Math.max(0,Math.floor((cancelDeadline(inv)-now())/36e5));
SCREENS.invoices={sec:'invoices',einv:true,title:()=>'Invoices',help:['An e-invoice is a digital invoice that LHDN checks. This page lists every one you made.','The coloured label shows the status. Tap a row to see what to do next.','"Waiting" lists sales where the customer asked for an e-invoice that has not been made yet.'],
 html(p){const f=p.f||'all',q=(p.q||'').trim().toLowerCase(),T=today(),wait=S.sales.filter(x=>x.want&&x.status==='paid'&&!x.inv).sort((a,b)=>b.no-a.no);
  const pm=addMonth(T.slice(0,7),-1),due=T.slice(0,7)+'-07',needCons=!S.cons[pm]&&consDays(pm).length>0;
  const fl=[['all','All',S.invoices.length],['wait','Waiting',wait.length],['Draft','Drafts',0],['Valid','Valid',0],['Invalid','Invalid',0],['Cancelled','Cancelled',0],['sup','From suppliers',S.bills.length]];fl.forEach(x=>{if(IST[x[0]])x[2]=S.invoices.filter(i=>i.status===x[0]).length});
  let body;
  if(f==='wait')body=wait.length?`<table><tr><th>Receipt</th><th>When</th><th class="r">Total</th><th></th></tr>${wait.map(s=>`<tr class="click" tabindex="0" ${A('go',{s:'invWiz',p:{sale:s.id}})}><td class="b">${s.no}</td><td>${fDT(s.dt)}</td><td class="r">${rm(s.total)}</td><td class="chev">Issue e-invoice ›</td></tr>`).join('')}</table>`:empty('No sales are waiting','When a customer asks for an e-invoice, it shows up here until you issue it.',`<button class="btn sec" ${A('set',{k:'f',v:'all'})}>See all e-invoices</button>`);
  else if(f==='sup')body=S.bills.length?`<table><tr><th>Bill</th><th>Supplier</th><th class="r">Amount</th><th>E-invoice from supplier</th><th></th></tr>${S.bills.map(b=>`<tr class="click" tabindex="0" ${A('go',{s:'bill',p:{id:b.id}})}><td class="b">${h(b.no)}</td><td>${h(SUP(b.sup).name)}</td><td class="r">${rm(b.amount)}</td><td>${einvPill(b.einv)}</td><td class="chev">Open ›</td></tr>`).join('')}</table>`:empty('No supplier bills yet','');
  else{const rows=S.invoices.slice().reverse().filter(i=>(f==='all'||i.status===f)&&(!q||i.no.toLowerCase().includes(q)||(i.buyer.name||'').toLowerCase().includes(q)||String(i.receipt||'').includes(q)));
   body=rows.length?`<table><tr><th>Number</th><th class="hide-s">Type</th><th>Buyer</th><th class="hide-s">Receipt</th><th class="r">Total</th><th>Status</th><th></th></tr>${rows.map(i=>`<tr class="click" tabindex="0" ${A('go',{s:'inv',p:{id:i.id}})}><td class="b">${h(i.no)}</td><td class="hide-s">${invKind(i)}</td><td>${h(i.buyer.name||'(not filled in yet)')}</td><td class="hide-s">${i.receipt||'-'}</td><td class="r">${rm(i.tot.payable)}</td><td>${pill(...IST[i.status])}</td><td class="chev">Open ›</td></tr>`).join('')}</table>`
    :empty(q?'Nothing matches "'+h(q)+'"':f==='all'?'No e-invoices yet':'No e-invoices with this status',q?'':'Issue one from a sale.',q?`<button class="btn sec" ${A('set',{k:'q',v:''})}>Clear search</button>`:f==='all'?`<button class="btn" ${A('go',{s:'pickSale'})}>Issue your first e-invoice</button>`:`<button class="btn sec" ${A('set',{k:'f',v:'all'})}>See all e-invoices</button>`)}
  return `${pageHead('Invoices','E-invoices you issued, and the ones your suppliers sent you.'+tip('einv'),`<button class="btn" id="issuebtn" ${A('go',{s:'pickSale'})}>${ic('plus')}Issue e-invoice</button><button class="btn sec" ${A('go',{s:'notes'})}>E-invoice notes</button>`)}
  ${needCons?`<button class="alert ${T>due?'bad':'warn'}" id="consalert" ${A('go',{s:'invWiz',p:{cons:pm}})}><span class="ai">${ic('file')}</span><span class="grow" style="text-align:left">Combined e-invoice for ${fM(pm)} walk-in sales is ${T>due?'overdue':'due by '+fD(due)}<small>One e-invoice covers every sale where nobody asked for their own. LHDN wants it within 7 days after the month ends.</small></span><span class="go">Create it${ic('chev')}</span></button>`:''}
  <div class="tabs">${fl.map(([k,l,n])=>`<button class="tab ${f===k?'on':''}" ${A('set',{k:'f',v:k})}>${l} <span class="n">(${n})</span></button>`).join('')}</div>
  ${f!=='wait'&&f!=='sup'?`<div class="row">${searchBox('q','Search by number, buyer or receipt',p.q)}</div>`:''}<div class="card pad0"><div class="tw">${body}</div></div>`}};
SCREENS.pickSale={sec:'invoices',einv:true,title:()=>'Pick the sale',help:['Choose the sale the customer wants an e-invoice for.','Type the receipt number from their receipt to find it fast.','Only sales from the last few days without an e-invoice are listed.'],
 html(p){const q=(p.q||'').trim(),rows=S.sales.filter(s=>s.status==='paid'&&!s.inv&&(!q||String(s.no).includes(q))).sort((a,b)=>b.no-a.no).slice(0,60);
  return `${pageHead('Which sale is this e-invoice for?','Ask the customer for their receipt number.')}<div class="row">${searchBox('q','Type the receipt number',p.q)}</div>
  <div class="card pad0"><div class="tw">${rows.length?`<table><tr><th>Receipt</th><th>When</th><th class="hide-s">Type</th><th class="r">Total</th><th></th></tr>${rows.map(s=>`<tr class="click" tabindex="0" ${A('go',{s:'invWiz',p:{sale:s.id}})}><td class="b">${s.no} ${s.want?pill('Waiting','warn'):''}</td><td>${fDT(s.dt)}</td><td class="hide-s">${s.type==='dine'?'Table '+h(s.table):'Takeaway'}</td><td class="r">${rm(s.total)}</td><td class="chev">Pick ›</td></tr>`).join('')}</table>`
   :empty(q?'No receipt matches "'+h(q)+'"':'No sales to invoice','Check the number on the receipt. Sales that already have an e-invoice are not listed.',q?`<button class="btn sec" ${A('set',{k:'q',v:''})}>Clear search</button>`:`<button class="btn" ${A('root',{s:'pos'})}>Make a sale first</button>`)}</div></div>
  <div class="foot"><button class="btn sec" ${A('back')}>Cancel</button></div>`}};
function invDoc(inv){const c=S.settings.cafe,b=inv.buyer;return`<div class="grid g2">
  <div class="card"><h3>Supplier (your business)</h3><dl class="kv" style="margin-top:8px"><dt>Name</dt><dd>${h(c.legal)}</dd><dt>TIN ${tip('tin')}</dt><dd>${h(c.tin)}</dd><dt>Registration no. ${tip('brn')}</dt><dd>${h(c.brn)}</dd><dt>SST no.</dt><dd>${h(c.sst)||'NA'}</dd><dt>Activity code ${tip('msic')}</dt><dd>${h(c.msic)} ${h(c.activity)}</dd><dt>Address</dt><dd>${h(c.addr)}, ${h(c.post)} ${h(c.city)}, ${h(c.state)}</dd><dt>Phone</dt><dd>${h(c.phone)}</dd></dl></div>
  <div class="card"><h3>Buyer</h3><dl class="kv" style="margin-top:8px"><dt>Name</dt><dd>${h(b.name)||'<span class="red-t">Missing</span>'}</dd><dt>TIN</dt><dd>${h((b.tin||'').toUpperCase())||'<span class="red-t">Missing</span>'}</dd><dt>ID (${h(b.idType||'')})</dt><dd>${h(b.idNo)||'<span class="red-t">Missing</span>'}</dd><dt>SST no.</dt><dd>${h(b.sst)||'NA'}</dd><dt>Address</dt><dd>${[b.addr,[b.post,b.city].filter(Boolean).join(' '),b.state].filter(x=>x&&x!=='NA').map(h).join(', ')||'NA'}</dd><dt>Phone</dt><dd>${h(b.phone)||'<span class="red-t">Missing</span>'}</dd><dt>Email</dt><dd>${h(b.email)||'-'}</dd></dl></div></div>
  <div class="card"><h3>Document</h3><dl class="kv" style="margin-top:8px"><dt>Number</dt><dd>${h(inv.no)}</dd><dt>Type</dt><dd>${inv.type==='02'?'02 Credit note':'01 Invoice'} · version 1.1</dd><dt>Date and time</dt><dd>${fDT(inv.issued||inv.created)}</dd><dt>Currency</dt><dd>MYR</dd>${inv.receipt?`<dt>Receipt</dt><dd>${inv.receipt}</dd>`:''}${inv.type==='02'?`<dt>Corrects</dt><dd>${h(inv.refNo)} (${h(inv.refUuid||'no ID')})</dd><dt>Reason</dt><dd>${h(inv.reason)||'<span class="red-t">Missing</span>'}</dd>`:''}</dl></div>
  ${invLines(inv)}`}
function invLines(inv){return`<div class="card pad0"><div class="tw"><table><tr><th>Description</th><th>Code${tip('cls')}</th><th class="r">Qty</th><th class="r">Unit price</th><th class="r">Amount</th><th>Tax type${tip('taxt')}</th><th class="r">Rate</th><th class="r">Tax</th></tr>
  ${inv.lines.map(l=>`<tr><td>${h(l.desc)}</td><td>${l.cls}</td><td class="r">${l.qty}</td><td class="r">${amt(l.unit)}</td><td class="r">${amt(l.amt)}</td><td>${l.taxType} ${TAXT[l.taxType]}</td><td class="r">${l.rate}%</td><td class="r">${amt(l.tax)}</td></tr>`).join('')}
  <tr><td colspan="7" class="r">Total excluding tax</td><td class="r">${amt(inv.tot.excl)}</td></tr><tr><td colspan="7" class="r">Total tax</td><td class="r">${amt(inv.tot.tax)}</td></tr><tr><td colspan="7" class="r">Total including tax</td><td class="r">${amt(inv.tot.incl)}</td></tr><tr><td colspan="7" class="r">Rounding</td><td class="r">${amt(inv.tot.round)}</td></tr><tr><td colspan="7" class="r b">Total payable (MYR)</td><td class="r b">${amt(inv.tot.payable)}</td></tr></table></div></div>`}
const WSTEPS={single:['Buyer details','Check items','Review','Submit'],consolidated:['Pick month','Check items','Review','Submit'],credit:['Reason','Check items','Review','Submit']};
const errBox=(errs,inv)=>errs.length?`<div class="errs" role="alert" id="errbox">${errs.map(e=>`<div class="e"><span>${h(e.msg)}</span><button class="btn sec sm" ${e.f==='cafe'?A('go',{s:'setBiz'}):A('invFix',{f:e.f,step:e.step})}>Fix it</button></div>`).join('')}</div>`:'';
SCREENS.invWiz={sec:'invoices',einv:true,title:p=>{const i=invBy(p.inv);return i?(i.type==='02'?'Credit note':i.kind==='consolidated'?'Combined e-invoice':'E-invoice')+' '+i.no:'New e-invoice'},
 help:['There are 4 steps, shown in the bar at the top. The green button always takes you to the next one.','If something is missing, a red box tells you what and a "Fix it" button takes you to the field.','Nothing is sent to LHDN. This is a practice run.'],
 html(p){
  if(!p.inv){let inv;if(p.sale){const s=saleBy(p.sale);if(!s)return saleMissing();if(s.inv)return empty('This sale already has an e-invoice','You can open it, or cancel it there first if it is wrong.',`<button class="btn" ${A('go',{s:'inv',p:{id:s.inv}})}>Open its e-invoice</button>`);if(s.status!=='paid')return empty('This sale was voided','A voided sale cannot get an e-invoice.',`<button class="btn" ${A('back')}>Go back</button>`);const ex=S.invoices.find(i=>i.kind==='single'&&i.type==='01'&&i.sales[0]===s.id&&(i.status==='Draft'||i.status==='Invalid'));inv=ex||invFromSale(s);if(!ex)S.invoices.push(inv);if(inv.status==='Invalid')inv.status='Draft'}
   else if(p.cons){inv=S.invoices.find(i=>i.kind==='consolidated'&&i.month===p.cons&&i.status==='Draft');if(!inv){inv=invConsolidated(p.cons);S.invoices.push(inv)}}
   else if(p.credit){const o=invBy(p.credit);inv=invCreditNote(o,'');S.invoices.push(inv)}
   if(!inv)return empty('Nothing to invoice','',`<button class="btn" ${A('root',{s:'invoices'})}>Back to Invoices</button>`);p.inv=inv.id;p.step=p.step||1;save()}
  const inv=invBy(p.inv);if(!inv)return empty('This draft was deleted','',`<button class="btn" ${A('root',{s:'invoices'})}>Back to Invoices</button>`);
  BIND=inv;const kind=inv.kind,steps=stepsBar(WSTEPS[kind],p.step-1),b=inv.buyer,errs=validateInv(inv),e1=errs.filter(e=>e.step<=1),has=f=>p.tried&&errs.some(e=>e.f===f)?'err':'';
  const exit=`<button class="btn sec" ${A('invExit')}>Save draft and close</button>`;
  if(inv.status==='Submitted'||p.step===4){
   if(inv.status==='Submitted')return `${steps}<div class="card donebox"><span class="tick wait">${ic('clock')}</span><h1>Sending to LHDN (pretend)...</h1><p class="muted">Status: ${pill('Submitted','info')} Waiting for the check. This takes a moment.</p><div class="acts"><button class="btn sec" ${A('invCheck',{id:inv.id})}>Check status now</button></div></div>`;
   if(inv.status==='Valid')return `${steps}<div class="card donebox"><span class="tick">${ic('check')}</span><h1>${inv.type==='02'?'Credit note':'E-invoice'} ${h(inv.no)} is valid</h1><p>${pill('Valid','ok')} ${ISTX.Valid}</p><p class="muted">You can cancel it within ${S.settings.cancelHours} hours if something is wrong. After that you need a credit note.</p>
     <div class="acts"><button class="btn big" id="openinv" ${A('invOpen',{id:inv.id})}>Open the e-invoice</button>${S.role==='cashier'?`<button class="btn sec big" ${A('root',{s:'pos'})}>New sale</button>`:`<button class="btn sec big" ${A('root',{s:'invoices'})}>Back to Invoices</button>`}</div></div>`;
   if(inv.status==='Invalid')return `${steps}<div class="card donebox"><span class="tick bad">${ic('x')}</span><h1>LHDN rejected this e-invoice</h1><p>${pill('Invalid','bad')} ${h((inv.errors||[]).join(' '))}</p><p class="muted">Check the buyer TIN and ID number with the customer, fix them, then send again.</p><div class="acts"><button class="btn big" ${A('invFix',{f:'tin',step:1})}>Fix buyer details</button><button class="btn sec big" ${A('invExit')}>Fix it later</button></div></div>`;
   p.step=3}
  if(p.step===1){let mid;
   if(kind==='consolidated'){const T=today(),ms=[-1,0].map(k=>addMonth(T.slice(0,7),k)).filter(m=>consDays(m).length&&!S.cons[m]);if(!ms.includes(inv.month))ms.unshift(inv.month);
    mid=`<div class="card" style="display:flex;flex-direction:column;gap:12px"><h2>Which month?${tip('cons')}</h2><div class="chips">${ms.map(m=>`<button class="chip ${inv.month===m?'on':''}" aria-pressed="${inv.month===m}" ${A('consMonth',{m})}>${fM(m)}</button>`).join('')}</div>
     <p>${plural(inv.lines.length,'day')} of walk-in sales, ${rm(inv.tot.payable)} in total. Sales that already have their own e-invoice are left out.</p>
     <dl class="kv"><dt>Buyer name</dt><dd>General Public</dd><dt>Buyer TIN</dt><dd>EI00000000010</dd><dt>Other buyer details</dt><dd>NA</dd></dl><p class="muted sm">LHDN sets these buyer details for combined e-invoices, so there is nothing to type.</p></div>`}
   else if(kind==='credit'){const o=invBy(inv.ref);mid=`<div class="card" style="display:flex;flex-direction:column;gap:12px"><h2>Why is a credit note needed?${tip('cn')}</h2><p>This credit note reverses e-invoice <b>${h(inv.refNo)}</b> (${rm(o?o.tot.payable:inv.tot.payable)}) for ${h(b.name)}.</p>
     <div class="chips">${['Wrong items or amounts','Customer returned the order','Wrong buyer details'].map(r=>`<button class="chip ${inv.reason===r?'on':''}" ${A('cnReason',{r})}>${r}</button>`).join('')}</div>${field('f-reason','Reason (you can type your own)',`<input class="inp ${has('reason')}" id="f-reason" data-m="@reason" data-save value="${h(inv.reason||'')}">`)}</div>`}
   else{const idT=b.type==='biz'?[['BRN','Business registration no.']]:b.type==='my'?[['NRIC','MyKad number']]:[['PASSPORT','Passport number']];
    mid=`<div class="card" style="display:flex;flex-direction:column;gap:14px"><div><div class="flabel" style="margin-bottom:6px">Quick fill for the demo (made-up buyers)</div><div class="chips">${BUYERS.map((x,i)=>`<button class="chip" ${A('invBuyer',{i})}>${h(x.label)}</button>`).join('')}</div></div>
     <div><div class="flabel" style="margin-bottom:6px">Who is the buyer?</div><div class="chips">${[['biz','A business'],['my','A Malaysian person'],['fo','A foreign person']].map(([k,l])=>`<button class="chip ${b.type===k?'on':''}" aria-pressed="${b.type===k}" ${A('invType',{t:k})}>${l}</button>`).join('')}</div></div>
     <div class="fgrid">${field('f-name',b.type==='biz'?'Registered business name':'Full name as on ID',`<input class="inp ${has('name')}" id="f-name" data-m="@buyer.name" data-save value="${h(b.name||'')}">`)}
      ${field('f-tin','TIN',`<input class="inp ${has('tin')}" id="f-tin" data-m="@buyer.tin" data-save value="${h(b.tin||'')}" placeholder="${b.type==='biz'?'For example C12345678900':'For example IG12345678900'}">`,'tin')}
      ${field('f-idNo',idT[0][1],`<input class="inp ${has('idNo')}" id="f-idNo" data-m="@buyer.idNo" data-save value="${h(b.idNo||'')}">`,b.type==='biz'?'brn':null)}
      ${field('f-sst','SST number (leave empty if none)',`<input class="inp" id="f-sst" data-m="@buyer.sst" data-save value="${h(b.sst||'')}">`,'sst')}
      ${field('f-addr','Address',`<input class="inp ${has('addr')}" id="f-addr" data-m="@buyer.addr" data-save value="${h(b.addr||'')}">`)}${field('f-city','City',`<input class="inp ${has('city')}" id="f-city" data-m="@buyer.city" data-save value="${h(b.city||'')}">`)}
      ${field('f-post','Postcode',`<input class="inp" id="f-post" inputmode="numeric" data-m="@buyer.post" data-save value="${h(b.post||'')}">`)}${field('f-state','State',`<select class="inp" id="f-state" data-m="@buyer.state" data-save>${STATES.map(s=>`<option ${b.state===s?'selected':''}>${s}</option>`).join('')}</select>`)}
      ${field('f-phone','Phone',`<input class="inp ${has('phone')}" id="f-phone" inputmode="tel" data-m="@buyer.phone" data-save value="${h(b.phone||'')}">`)}${field('f-email','Email (to send the e-invoice to)',`<input class="inp ${has('email')}" id="f-email" inputmode="email" data-m="@buyer.email" data-save value="${h(b.email||'')}">`)}</div></div>`}
   return `${pageHead(kind==='consolidated'?'Combined e-invoice for walk-in sales':kind==='credit'?'Credit note':'E-invoice for receipt '+inv.receipt,kind==='single'?'Ask the customer for these details. Everything else is filled in from the sale.':'')}${steps}${p.tried?errBox(e1,inv):''}${mid}
    <div class="foot">${exit}<div class="rt"><button class="btn big" id="wiznext" ${A('invNext')}>Save and go to Check items</button></div></div>`}
  if(p.step===2){const e2=errs.filter(e=>e.step===2);return `${pageHead('Check the items','These came straight from the '+(kind==='consolidated'?'daily sales':'receipt')+'. You only need to look them over.')}${steps}${errBox(e2,inv)}${invLines(inv)}
    <div class="card row">${e2.length?pill('Totals need fixing','bad'):`${pill('Totals add up','ok')}<span class="muted">Items + tax + rounding = ${rm(inv.tot.payable)}${inv.receipt?', the same as receipt '+inv.receipt:''}.</span>`}</div>
    <div class="foot"><button class="btn sec" ${A('set',{k:'step',v:1})}>${ic('back')}Back to ${WSTEPS[kind][0].toLowerCase()}</button><div class="rt">${e2.length?`<button class="btn sec" ${A('invRecalc')}>Work the totals out again</button>`:''}<button class="btn big" id="wiznext" ${A('set',{k:'step',v:3})}>Looks right, go to Review</button></div></div>`}
  return `${pageHead('Review before sending','This is everything that would go to LHDN, laid out the way LHDN lists the fields.')}${steps}${errBox(errs,inv)}${invDoc(inv)}
   <div class="foot"><button class="btn sec" ${A('set',{k:'step',v:2})}>${ic('back')}Back to items</button><div class="rt">${errs.length?'<span class="why">Fix the points in the red box first.</span>':''}<button class="btn big" id="wizsubmit" ${A('invSubmit')} ${errs.length?'disabled':''}>Submit e-invoice (demo)</button></div></div>`}};
function resolveInv(inv){if(inv.status!=='Submitted')return;if(simulateOutcome(inv)==='Valid')applyValid(inv);else applyInvalid(inv);save();const c=cur();if((c.s==='invWiz'&&c.p.inv===inv.id)||(c.s==='inv'&&c.p.id===inv.id)||c.s==='invoices'||c.s==='home')render(true)}
Object.assign(ACT,{
 invBuyer:p=>{const inv=invBy(cur().p.inv),x={...BUYERS[p.i]};delete x.label;inv.buyer=x;save();render(true);toast('Buyer details filled in')},
 invType:p=>{const inv=invBy(cur().p.inv);inv.buyer.type=p.t;inv.buyer.idType=p.t==='biz'?'BRN':p.t==='my'?'NRIC':'PASSPORT';save();render(true)},
 invNext:()=>{const p=cur().p,inv=invBy(p.inv);p.tried=1;if(inv.buyer.tin)inv.buyer.tin=inv.buyer.tin.trim().toUpperCase();if(validateInv(inv).some(e=>e.step===1)){save();render();const b=document.getElementById('errbox');if(b)b.scrollIntoView({block:'center'});toast('Fix the '+plural(validateInv(inv).filter(e=>e.step<=1).length,'point')+' in the red box first.');return}p.tried=0;p.step=2;save();render()},
 invFix:p=>{const c=cur(),inv=invBy(c.s==='invWiz'?c.p.inv:c.p.id);if(inv&&inv.status==='Invalid'){inv.status='Draft';save()}if(c.s!=='invWiz'){go('invWiz',{inv:c.p.id,step:p.step,tried:1});return}c.p.step=p.step;c.p.tried=1;render();setTimeout(()=>{const f=document.getElementById('f-'+p.f);if(f){f.scrollIntoView({block:'center'});f.focus()}},0)},
 invRecalc:()=>{const inv=invBy(cur().p.inv);inv.lines.forEach(l=>{if(!l.agg)l.tax=Math.round(l.amt*l.rate/100)});invTotals(inv);save();render(true);toast('Totals worked out again')},
 invExit:()=>{save();const inv=invBy(cur().p.inv);if(S.role==='cashier')root('pos');else root('invoices',{f:'Draft'});toast('Draft '+(inv?inv.no:'')+' saved. Find it under Invoices, Drafts.')},
 consMonth:p=>{const c=cur().p,old=invBy(c.inv);S.invoices=S.invoices.filter(i=>i!==old);const inv=invConsolidated(p.m);S.invoices.push(inv);c.inv=inv.id;save();render(true)},
 cnReason:p=>{invBy(cur().p.inv).reason=p.r;save();render(true)},
 invSubmit:()=>{const p=cur().p,inv=invBy(p.inv);if(validateInv(inv).length)return;inv.status='Submitted';inv.issued=isoDT(now());p.step=4;save();render();setTimeout(()=>resolveInv(inv),1400)},
 invCheck:p=>resolveInv(invBy(p.id)),
 invOpen:p=>{const base=stack[0].s==='pos'?[stack[0]]:[{s:'invoices',p:{}}];stack=base.concat([{s:'inv',p:{id:p.id}}]);render()},
 invDelete:p=>{const inv=invBy(p.id);confirmBox({title:'Delete this draft?',body:'Draft '+h(inv.no)+' will be removed. It was never sent, so nothing else changes.',ok:'Yes, delete the draft',no:'No, keep it',danger:true,yes:()=>{S.invoices=S.invoices.filter(i=>i!==inv);save();root('invoices');toast('Draft deleted',()=>{S.invoices.push(inv)})}})},
 invCancel:p=>{const inv=invBy(p.id);modal(M=>`${mHead('Cancel e-invoice '+h(inv.no)+'?')}<p>The e-invoice will be marked as <b>Cancelled</b> and will no longer count. ${inv.kind==='single'?'The sale itself stays, and you can issue a new e-invoice for it.':''} You cannot undo this.</p><div class="flabel">Why? (LHDN asks for a reason)</div><div class="chips">${['Wrong buyer details','Wrong items or amounts','Issued by mistake'].map(r=>`<button class="chip ${M.r===r?'on':''}" aria-pressed="${M.r===r}" ${A('mset',{k:'r',v:r})}>${r}</button>`).join('')}</div>
   <div class="mf">${M.r?'':'<span class="why">Pick a reason first.</span>'}<button class="btn sec" ${A('closeModal')}>No, keep it</button><button class="btn red solid" id="cancelyes" ${A('invCancelDo',{id:inv.id})} ${M.r?'':'disabled'}>Yes, cancel this e-invoice</button></div>`,{r:''})},
 invCancelDo:p=>{const inv=invBy(p.id);if(!canCancel(inv)){closeModal();toast('The '+S.settings.cancelHours+'-hour limit has passed. Issue a credit note instead.');render(true);return}cancelInv(inv,M.r);closeModal();render();toast('E-invoice '+inv.no+' cancelled')},
 invJson:p=>{const inv=invBy(p.id);TEXTS.invJson=()=>JSON.stringify(invJSON(inv),null,1);TEXTS.invJson.file=inv.no+'.json';showText('E-invoice '+inv.no+' as JSON (simplified UBL 2.1 layout)','invJson')}
});
SCREENS.inv={sec:'invoices',einv:true,title:p=>{const i=invBy(p.id);return i?i.no:'E-invoice'},help:['The coloured label at the top is the status. The line next to it says what to do next.','A valid e-invoice can be cancelled for 72 hours. After that, use "Issue credit note".','"Show JSON" and "Printable view" are the two ways to take the e-invoice out of the app.'],
 html(p){const inv=invBy(p.id);if(!inv)return empty('This e-invoice was removed','',`<button class="btn" ${A('root',{s:'invoices'})}>Back to Invoices</button>`);
  const st=inv.status,cc=canCancel(inv),cn=S.invoices.find(i=>i.type==='02'&&i.ref===inv.id&&i.status!=='Cancelled'&&i.status!=='Draft');let acts='',note='';
  if(st==='Draft')acts=`<button class="btn" ${A('go',{s:'invWiz',p:{inv:inv.id,step:1}})}>Continue this e-invoice</button><button class="btn red" ${A('invDelete',{id:inv.id})}>Delete draft</button>`;
  else if(st==='Submitted')acts=`<button class="btn" ${A('invCheck',{id:inv.id})}>Check status now</button>`;
  else if(st==='Invalid')acts=`<button class="btn" ${A('invFix',{f:'tin',step:1})}>Fix and send again</button>`;
  else if(st==='Valid'){acts=`<button class="btn sec" ${A('go',{s:'invPrint',p:{id:inv.id}})}>Printable view</button><button class="btn sec" ${A('invJson',{id:inv.id})}>Show JSON</button>`;
   if(inv.type==='01'&&!cn)acts+=`<button class="btn sec" id="cnbtn" ${A('go',{s:'invWiz',p:{credit:inv.id}})}>Issue credit note</button>`;
   acts+=`<button class="btn red" id="cancelbtn" ${A('invCancel',{id:inv.id})} ${cc?'':'disabled'}>Cancel this e-invoice</button>`;
   note=cc?`You can cancel until <b>${fDT(isoDT(cancelDeadline(inv)))}</b> (${hoursLeft(inv)} hours left).`:`<span class="why">The ${S.settings.cancelHours}-hour limit for cancelling has passed. To reverse it, press "Issue credit note".</span>`}
  else if(st==='Cancelled'&&inv.kind==='single'){const s=saleBy(inv.sales[0]);if(s&&!s.inv&&s.status==='paid')acts=`<button class="btn" ${A('go',{s:'invWiz',p:{sale:s.id}})}>Issue a new e-invoice for this sale</button>`}
  const sale=inv.kind!=='consolidated'&&saleBy(inv.sales[0]);
  return `${pageHead(h(inv.no),`${pill(...IST[st])} ${invKind(inv)} · ${rm(inv.tot.payable)}`,acts)}
  <div class="card" style="display:flex;flex-direction:column;gap:8px"><p><b>What this status means:</b> ${ISTX[st]}</p>${st==='Invalid'?`<p class="red-t b">${h((inv.errors||[]).join(' '))}</p>`:''}${st==='Cancelled'?`<p>Reason given: ${h(inv.cancelReason||'-')}${inv.cancelled?' · cancelled '+fDT(inv.cancelled):''}</p>`:''}${note?`<p>${note}</p>`:''}${cn?`<p>${pill('Has a credit note','info')} <button class="btn sec sm" ${A('go',{s:'inv',p:{id:cn.id}})}>Open credit note ${h(cn.no)}</button></p>`:''}
   ${sale?`<div><button class="btn sec sm" ${A('go',{s:'receipt',p:{id:sale.id}})}>Open receipt ${sale.no}</button></div>`:''}</div>
  ${st==='Valid'||st==='Cancelled'?`<div class="card row" style="align-items:flex-start">${fakeQR(inv.uuid||inv.no)}<dl class="kv grow"><dt>Unique ID ${tip('uuid')}</dt><dd>${h(inv.uuid)}</dd><dt>Checked on</dt><dd>${fDT(inv.validated)}</dd><dt>Check link</dt><dd class="muted">A real e-invoice has a link and QR code that open LHDN's site. This demo shows a placeholder picture that cannot be scanned.</dd></dl></div>`:''}
  ${invDoc(inv)}`}};
SCREENS.invPrint={sec:'invoices',einv:true,title:()=>'Printable view',help:['This is how the e-invoice looks on paper or as a PDF.','When the app is opened from your own web link, a Print button appears here. In the print window choose "Save as PDF".','The big DEMO stamp stays on because this is not a real tax document.'],
 html(p){const inv=invBy(p.id);if(!inv)return empty('This e-invoice was removed','',`<button class="btn" ${A('root',{s:'invoices'})}>Back to Invoices</button>`);const c=S.settings.cafe,b=inv.buyer;
  return `${pageHead('Printable view','',STANDALONE?`<button class="btn" ${A('print')}>Print or save as PDF</button>`:'')}${STANDALONE?'':'<p class="muted sm noprint">To print or save as PDF, open the app from your own web link (GitHub Pages) instead of the Claude preview. A Print button shows up here.</p>'}
  <div class="paper a4"><div class="row" style="align-items:flex-start"><div class="grow"><div style="font-family:var(--display);font-size:22px;color:var(--green)">🥬 ${h(c.name)}</div><div>${h(c.legal)}<br>${h(c.addr)}, ${h(c.post)} ${h(c.city)}, ${h(c.state)}<br>TIN ${h(c.tin)} · Reg. ${h(c.brn)} · SST ${h(c.sst)}</div></div>${fakeQR(inv.uuid||inv.no)}</div>
   <hr><div class="row" style="align-items:flex-start"><div class="grow"><b>${inv.type==='02'?'CREDIT NOTE':'E-INVOICE'} ${h(inv.no)}</b><br>Date: ${fDT(inv.issued||inv.created)}<br>Unique ID: ${h(inv.uuid||'-')}<br>Status: ${inv.status}${inv.type==='02'?'<br>Corrects: '+h(inv.refNo):''}</div><div class="grow"><b>Bill to</b><br>${h(b.name)}<br>TIN ${h(b.tin)} · ID ${h(b.idNo)}<br>${[b.addr,b.post,b.city,b.state].filter(x=>x&&x!=='NA').map(h).join(', ')}</div></div><hr>
   <div class="tw"><table><tr><th>Description</th><th class="r">Qty</th><th class="r">Amount</th><th class="r">Tax</th></tr>${inv.lines.map(l=>`<tr><td>${h(l.desc)}</td><td class="r">${l.qty}</td><td class="r">${amt(l.amt)}</td><td class="r">${amt(l.tax)} (${l.rate}%)</td></tr>`).join('')}</table></div><hr>
   <div class="l"><span>Total excluding tax</span><span>${amt(inv.tot.excl)}</span></div><div class="l"><span>Service tax</span><span>${amt(inv.tot.tax)}</span></div><div class="l"><span>Rounding</span><span>${amt(inv.tot.round)}</span></div><div class="l b" style="font-size:17px"><span>Total payable (MYR)</span><span>${amt(inv.tot.payable)}</span></div><hr>
   <div style="text-align:center;color:var(--red);font-weight:800">DEMO - not connected to LHDN MyInvois. Not a valid tax document.</div></div>`}};

/* ---------- E-invoice notes (what was checked, with sources) ---------- */
const SRC={g:['LHDN e-Invoice Guideline, version 4.8 (30 Aug 2026)','https://www.hasil.gov.my/wp-content/uploads/IRBM-e-Invoice-Guideline.pdf'],s:['LHDN e-Invoice Specific Guideline, version 4.9 (7 Sep 2026)','https://www.hasil.gov.my/wp-content/uploads/IRBM-e-Invoice-Specific-Guideline.pdf'],
 t:['LHDN e-Invoice implementation timeline page','https://www.hasil.gov.my/en/e-invoice/implementation-of-e-invoicing-in-malaysia/e-invoice-implementation-timeline/'],d:['MyInvois SDK: Invoice v1.1 fields','https://sdk.myinvois.hasil.gov.my/documents/invoice-v1-1/'],
 c:['MyInvois SDK: Cancel Document','https://sdk.myinvois.hasil.gov.my/einvoicingapi/03-cancel-document/'],f:['MyInvois SDK: FAQ','https://sdk.myinvois.hasil.gov.my/faq/'],x:['MyInvois SDK: tax type codes','https://sdk.myinvois.hasil.gov.my/codes/tax-types/'],k:['MyInvois SDK: classification codes','https://sdk.myinvois.hasil.gov.my/codes/classification-codes/'],
 m:['Royal Malaysian Customs (MySST): service tax FAQ','https://mysst.customs.gov.my/faq-services-tax/']};
const src=(...ks)=>ks.map(k=>`<a href="${SRC[k][1]}" target="_blank" rel="noopener">${SRC[k][0]}</a>`).join(' · ');
const NOTES_OK=[
 ['Format','An e-invoice is sent as XML or JSON in the UBL 2.1 layout. Invoice version 1.1 is the one where the digital signature is checked. The fields in this app follow that list (supplier, buyer, number, date and time, lines, tax type and amount, totals, currency).',['d']],
 ['How many fields','LHDN lists 55 data fields needed to issue an e-invoice. This demo fills the main ones and leaves out optional ones such as shipping and customs details.',['g']],
 ['Statuses','MyInvois uses four statuses: Submitted, Valid, Invalid, Cancelled. "Draft" in this app is our own word for "not sent yet".',['f']],
 ['Cancelling','The issuer can cancel within 72 hours from the time the e-invoice became valid, and must give a reason. After that the system refuses, so a credit note is needed.',['c','g']],
 ['Combined e-invoice for walk-in sales','If a customer does not ask for an e-invoice, the outlet gives a normal receipt and sends one consolidated e-invoice within 7 calendar days after the month ends. Buyer name is "General Public", buyer TIN is EI00000000010, and the other buyer details are "NA". Lines can be a list of receipt numbers. Classification code 004 marks a consolidated e-invoice.',['s','k']],
 ['The RM10,000 rule','From 1 January 2026 a single sale above RM10,000 cannot go into the combined e-invoice. It needs its own. Rare for a cafe, but it applies to catering orders.',['s']],
 ['When a customer asks for one','A Malaysian person gives a TIN, or a MyKad number, or both. A foreign person gives a TIN, or a passport number with LHDN\'s general TIN.',['s']],
 ['Who has to do it, and when','The phases: over RM100 million turnover from 1 Aug 2024; RM25 to 100 million from 1 Jan 2025; RM5 to 25 million from 1 Jul 2025; up to RM5 million from 1 Jan 2026. The guideline dated 30 Aug 2026 says businesses with yearly turnover below RM3,000,000 are exempt (with exceptions for businesses owned by, or related to, bigger companies). So most small cafes do not have to issue e-invoices today.',['g']],
 ['SST on food and drink','Food and drink services are taxed at 6% service tax (they stayed at 6% when the general rate went to 8% on 1 Mar 2024). An outlet only has to register once its yearly sales pass RM1,500,000. On the e-invoice this is tax type 02 (Service Tax).',['m','x']],
 ['QR code and ID','A valid e-invoice gets a unique ID from LHDN, and the QR code is made from a validation link that includes that ID.',['f']]];
const NOTES_NO=[
 'The LHDN timeline web page still says the exemption is "less than RM1,000,000" (page last updated 7 Dec 2025). The newer guideline PDF says RM3,000,000. This app follows the newer PDF. Ask LHDN or an accountant before relying on either number.',
 'The end date of LHDN\'s grace period for penalties was only seen on non-official websites, so it is left out.',
 'Whether service tax is charged on top of the service charge could not be confirmed from an official Customs page today. It is a switch in Settings, on by default.',
 'How a service charge should be shown on an e-invoice (as its own line, or as a fee on the invoice) was not confirmed. This demo shows it as its own line.',
 'The 5 sen rounding rule was not checked against a Bank Negara source today. It is a switch in Settings.',
 'The business activity code (MSIC) 56101 and classification code 022 (Others) for food items are placeholders. A real business must look up its own codes.',
 'The exact shape of a TIN was not checked. The app only looks for 1 or 2 letters followed by numbers.',
 'That a supplier\'s e-invoice is your proof of the expense is how LHDN describes it in general material, but the exact wording was not re-checked today.'];
SCREENS.notes={sec:'invoices',einv:true,title:()=>'E-invoice notes',help:['This page lists the LHDN rules this demo was built around.','Each point has a link to the official page it came from.','The second list is what could not be confirmed. Treat those as open questions.'],
 html(){return `${pageHead('E-invoice notes','What was checked against official sources on 7 October 2026, and what was not.')}
  <div class="card" style="background:var(--amber-s)"><b>Different from the original brief:</b> small outlets are mostly exempt. A cafe with yearly turnover under RM3 million does not have to issue e-invoices under the current guideline, and one under RM1.5 million does not charge SST. So for GoodBite's target customers, e-invoicing is a "ready when you grow, or when a company customer asks" feature, not a legal must-have today.</div>
  <div class="card"><h2>Checked against official sources</h2><div style="display:flex;flex-direction:column;gap:14px">${NOTES_OK.map(([t,b,s])=>`<div><b>${t}</b><p>${b}</p><p class="sm">Source: ${src(...s)}</p></div>`).join('')}</div></div>
  <div class="card"><h2>Not confirmed</h2><ul style="margin:0;padding-left:20px;display:flex;flex-direction:column;gap:8px">${NOTES_NO.map(x=>`<li>${x}</li>`).join('')}</ul><p class="sm" style="margin-top:10px">Also consulted: ${src('t')}</p></div>
  <div class="card"><h2>What a real product would still need</h2><p>Registration with MyInvois for API access, a digital certificate to sign each e-invoice, a real connection that sends the document and reads back LHDN's answer, and secure storage of every e-invoice. None of that exists in this demo.</p><div style="margin-top:10px"><button class="btn sec" ${A('go',{s:'limits'})}>See the full limitations list</button></div></div>`}};

/* ---------- Settings ---------- */
SCREENS.settings={sec:'settings',title:()=>'Settings',help:['Each card opens one group of settings.','Changes are saved as soon as you make them.','"Reset demo data" at the bottom puts everything back to how it started.'],
 html(){const card=(icn,t,d,a,p)=>`<button class="alert" ${A(a,p)}><span class="ai" style="background:var(--green-s);color:var(--green-d)">${ic(icn)}</span><span class="grow" style="text-align:left">${t}<small>${d}</small></span><span class="go">Open${ic('chev')}</span></button>`;
  return `${pageHead('Settings','Set the app up for your outlet.')}<div class="grid g2">
   ${card('home','Business details','Name, address, TIN and registration numbers used on receipts and e-invoices.','go',{s:'setBiz'})}${card('sliders','Tax, service charge and rounding','The percentages the till adds to each bill.','go',{s:'setTax'})}
   ${card('bag','Menu and recipes','Add, change or delete dishes, their prices and recipes.','go',{s:'menuList'})}${card('clock','Alerts','When to warn about food that is close to expiry.','go',{s:'setAlerts'})}
   ${card('file','E-invoice notes','The LHDN rules this demo follows, with sources.','go',{s:'notes'})}${card('alert','Limitations','What is pretend in this demo and what a real product still needs.','go',{s:'limits'})}
   ${card('user','Language · Bahasa · 语言','English, Bahasa Melayu or Chinese for the whole app.','go',{s:'setLang'})}
   ${card('help','Tours','Replay the welcome tour, or start the step-by-step demo tour.','help')}</div>
  <div class="card" style="display:flex;flex-direction:column;gap:10px;border-color:var(--red)"><h2>Reset demo data</h2><p>Puts back the made-up cafe: 44 dishes, 60 ingredients, 6 suppliers and 2 months of sales and waste. Everything you added or changed in this browser is erased.</p><div><button class="btn red" id="resetbtn" ${A('resetAsk')}>Reset demo data</button></div></div>`}};
ACT.resetAsk=()=>confirmBox({title:'Reset all demo data?',body:'Every sale, order, waste entry, e-invoice and setting you changed in this browser will be erased and replaced with the starting demo data. You cannot undo this.',ok:'Yes, reset everything',no:'No, keep my data',danger:true,yes:()=>{resetDemo();S.toured=true;save();root('home');toast('Demo data reset. Everything is back to the start.')}});
SCREENS.setBiz={sec:'settings',title:()=>'Business details',help:['These details print on receipts and go on every e-invoice.','All numbers here are made up. Replace them only for your own testing.','Changes save as you type.'],
 html(){const c=S.settings.cafe;BIND=c;const f=(k,l,t)=>field('sb-'+k,l,`<input class="inp" id="sb-${k}" data-m="@${k}" data-save value="${h(c[k])}">`,t);
  return `${pageHead('Business details','Used on receipts and e-invoices. '+pill('All numbers are made up','warn'))}<div class="card"><div class="fgrid">${f('name','Outlet name (on receipts)')}${f('legal','Registered business name')}${f('tin','TIN','tin')}${f('brn','Business registration number','brn')}${f('sst','SST registration number','sst')}${f('msic','Business activity code','msic')}${f('activity','Business activity description')}${f('addr','Address')}${f('post','Postcode')}${f('city','City')}
   ${field('sb-state','State',`<select class="inp" id="sb-state" data-m="@state" data-save>${STATES.map(s=>`<option ${c.state===s?'selected':''}>${s}</option>`).join('')}</select>`)}${f('phone','Phone')}${f('email','Email')}</div></div>
  <div class="foot"><span class="muted sm">Saved automatically as you type.</span><div class="rt"><button class="btn big" ${A('back')}>Done, back to Settings</button></div></div>`}};
SCREENS.setTax={sec:'settings',title:()=>'Tax and rounding',help:['Switch each charge on or off and set its percentage.','The example on the right shows what a RM 20.00 bill becomes.','Check the right rates with Customs or your accountant. The starting values are only common examples.'],
 html(){const t=S.settings.tax;BIND=t;const ex=billTotals([{price:2000,modTotal:0,qty:1}],'dine',t),ext=billTotals([{price:2000,modTotal:0,qty:1}],'take',t);
  return `${pageHead('Tax, service charge and rounding','These are starting values, not official rates for your outlet. Check before you rely on them.')}
  <div class="grid g2"><div class="card" style="display:flex;flex-direction:column;gap:6px">
   ${tog(t.scOn,'Add a service charge to dine-in bills','taxTog',{k:'scOn'},'sc')}${t.scOn?`<div class="row" style="padding-left:62px"><label for="tx-sc">Service charge %</label><input class="inp narrow" id="tx-sc" inputmode="decimal" data-m="@scRate" data-num data-r data-save value="${h(t.scRate)}"></div>${tog(t.scTakeaway,'Also add it to takeaway bills','taxTog',{k:'scTakeaway'})}`:''}
   <hr style="border:0;border-top:1px solid var(--line);width:100%">${tog(t.sstOn,'Charge SST (only if the outlet is registered for it)','taxTog',{k:'sstOn'},'sst')}${t.sstOn?`<div class="row" style="padding-left:62px"><label for="tx-sst">SST %</label><input class="inp narrow" id="tx-sst" inputmode="decimal" data-m="@sstRate" data-num data-r data-save value="${h(t.sstRate)}"></div>${tog(t.sstOnSc,'Charge SST on the service charge too','taxTog',{k:'sstOnSc'})}`:''}
   <hr style="border:0;border-top:1px solid var(--line);width:100%">${tog(t.round5,'Round the final bill to the nearest 5 sen','taxTog',{k:'round5'},'round')}</div>
  <div class="card" style="display:flex;flex-direction:column;gap:6px"><h2>Example: RM 20.00 of food, dine-in</h2>${totalsHtml(ex,t)}<p class="muted sm" style="margin-top:8px">The same order as takeaway comes to ${rm(ext.total)}.</p></div></div>
  <div class="foot"><span class="muted sm">Saved automatically. New bills use the new settings. Old receipts keep the rates they were sold at.</span><div class="rt"><button class="btn big" ${A('back')}>Done, back to Settings</button></div></div>`}};
ACT.taxTog=p=>{S.settings.tax[p.k]=!S.settings.tax[p.k];save();render(true)};
SCREENS.setAlerts={sec:'settings',title:()=>'Alerts',help:['Choose how early the app should warn you about food that is about to expire.','A bigger number gives you more time to use the food or offer it for rescue.','The change shows on Home and in Stock straight away.'],
 html(){const d=S.settings.expDays;return `${pageHead('Alerts','')}<div class="card" style="display:flex;flex-direction:column;gap:12px"><h2>Expiring soon</h2><p>Warn me when food has this many days left, or fewer:</p><div class="chips">${[1,2,3,5,7].map(n=>`<button class="chip ${d===n?'on':''}" aria-pressed="${d===n}" ${A('setExp',{n})}>${plural(n,'day')}</button>`).join('')}</div><p class="muted">Right now ${plural(soonList().length,'batch','batches')} would be on the "Expiring soon" list.</p></div>
  <div class="foot"><span class="muted sm">Saved automatically.</span><div class="rt"><button class="btn big" ${A('back')}>Done, back to Settings</button></div></div>`}};
ACT.setExp=p=>{S.settings.expDays=p.n;save();render(true);toast('Saved. Warning '+plural(p.n,'day')+' before expiry.')};
const recipeCost=m=>m.recipe.reduce((a,[g,q])=>a+Math.round(q*ING(g).cost),0);
const menuCats=()=>[...new Set([...MENU_CATS.filter(c=>S.menu.some(m=>m.cat===c)),...S.menu.map(m=>m.cat)])];
const DISH_PICS=['☕','🧊','🍵','🥤','🧃','🍳','🥑','🥯','🍞','🥞','🥣','🍛','🍚','🍜','🍝','🍔','🌯','🥪','🥗','🍟','🍗','🐟','🥐','🍰','🧁','🍫','🍪','🍌','🍽️'];
SCREENS.menuList={sec:'settings',title:()=>'Menu and recipes',help:['Every dish on the till is listed here with its price and what its ingredients cost.','Press "Add dish" to put a new dish on the menu. Tap a row to change or delete a dish.','The recipe is what the till takes off the stock each time the dish is sold.'],
 html(p){const q=(p.q||'').trim().toLowerCase(),rows=S.menu.filter(m=>!q||m.name.toLowerCase().includes(q)||m.id.includes(q));
  return `${pageHead('Menu and recipes',plural(S.menu.length,'dish','dishes')+' on the menu. '+demoTag,`<button class="btn" id="adddish" ${A('go',{s:'menuItem',p:{}})}>${ic('plus')}Add dish</button>`)}<div class="row">${searchBox('q','Search the menu',p.q)}</div>
  <div class="card pad0"><div class="tw">${rows.length?`<table><tr><th>Code</th><th>Dish</th><th class="hide-s">Group</th><th class="r">Price</th><th class="r hide-s">Ingredients cost</th><th class="r">Food cost</th><th></th></tr>${rows.map(m=>{const c=recipeCost(m);return`<tr class="click" tabindex="0" ${A('go',{s:'menuItem',p:{id:m.id}})}><td>${m.id}</td><td class="b">${m.e} ${h(m.name)}</td><td class="hide-s">${h(m.cat)}</td><td class="r">${rm(m.price)}</td><td class="r hide-s">${rm(c)}</td><td class="r">${m.price?(c/m.price*100).toFixed(0):0}%</td><td class="chev">Change ›</td></tr>`}).join('')}</table>`
   :S.menu.length?empty('No dish matches "'+h(q)+'"','Check the spelling or clear the search.',`<button class="btn sec" ${A('set',{k:'q',v:''})}>Clear search</button>`):empty('The menu is empty','Add the first dish so the till has something to sell.',`<button class="btn" ${A('go',{s:'menuItem',p:{}})}>Add your first dish</button>`)}</div></div>`}};
function dishErrs(d,id){const e=[];if(!d.name.trim())e.push(['md-name','The dish name is missing.']);else if(S.menu.some(m=>m.id!==id&&m.name.toLowerCase()===d.name.trim().toLowerCase()))e.push(['md-name','Another dish already has this name. Use a different name.']);
  if(!(num(d.price)>0))e.push(['md-price','The price is missing. Type a number above 0, for example 12.00.']);
  if(d.cat==='__new'&&!(d.newCat||'').trim())e.push(['md-newcat','Type a name for the new group, or pick an existing group.']);
  d.recipe.forEach((r,i)=>{if(!(num(r[1])>0))e.push(['md-q'+i,ING(r[0]).name+': type how much one portion uses, for example 0.2.'])});return e}
SCREENS.menuItem={sec:'settings',title:p=>p.id&&MENU(p.id)?MENU(p.id).name:'New dish',help:['Set the name, group and price. The picture and options are extras.','The recipe lists what one portion uses. Each sale takes these amounts off the stock, oldest batch first.','Press "Save dish" when you are done. "Delete dish" removes it from the till, but old receipts keep it.'],
 html(p){const m=p.id?MENU(p.id):null;if(p.id&&!m)return empty('This dish was deleted','',`<button class="btn" ${A('root',{s:'settings'})}>Back to Settings</button>`);
  if(!p.d)p.d=m?{name:m.name,cat:m.cat,newCat:'',price:amt(m.price),e:m.e,mods:m.mods.slice(),recipe:m.recipe.map(r=>[r[0],String(+(+r[1]).toFixed(4))]),add:''}:{name:'',cat:menuCats()[0]||'__new',newCat:'',price:'',e:'🍽️',mods:[],recipe:[],add:''};
  const d=p.d,errs=p.tried?dishErrs(d,p.id):[],has=id=>errs.some(e=>e[0]===id)?'err':'',cost=d.recipe.reduce((a,r)=>a+Math.round((num(r[1])||0)*ING(r[0]).cost),0),np=num(d.price),left=S.ingredients.filter(i=>!d.recipe.some(r=>r[0]===i.id));
  return `${pageHead(m?'Change dish: '+h(m.name):'Add a dish',m?'Code '+m.id+'. Changes reach the till when you press "Save dish".':'It shows on the till as soon as you save it.')}
  ${errs.length?`<div class="errs" role="alert">${errs.map(e=>`<div class="e"><span>${h(e[1])}</span><button class="btn sec sm" ${A('focus',{id:e[0]})}>Fix it</button></div>`).join('')}</div>`:''}
  <div class="card" style="display:flex;flex-direction:column;gap:14px"><h2>1. The dish</h2><div class="fgrid">
   ${field('md-name','Dish name',`<input class="inp ${has('md-name')}" id="md-name" data-m="d.name" value="${h(d.name)}" placeholder="For example: Iced Lemon Tea">`)}
   ${field('md-cat','Group on the till',`<select class="inp" id="md-cat" data-m="d.cat" data-r>${menuCats().map(c=>`<option value="${h(c)}" ${d.cat===c?'selected':''}>${h(c)}</option>`).join('')}<option value="__new" ${d.cat==='__new'?'selected':''}>Make a new group...</option></select>`)}
   ${d.cat==='__new'?field('md-newcat','Name of the new group',`<input class="inp ${has('md-newcat')}" id="md-newcat" data-m="d.newCat" value="${h(d.newCat)}" placeholder="For example: Desserts">`):''}
   ${field('md-price','Selling price (RM, before tax)',`<input class="inp ${has('md-price')}" id="md-price" inputmode="decimal" data-m="d.price" data-live value="${h(d.price)}" placeholder="0.00">`)}</div>
   <div><div class="flabel" style="margin-bottom:6px">Picture on the till button</div><div class="chips">${DISH_PICS.map(x=>`<button class="chip ${d.e===x?'on':''}" aria-pressed="${d.e===x}" aria-label="Picture ${x}" ${A('dishPic',{e:x})}>${x}</button>`).join('')}</div></div>
   <div><div class="flabel" style="margin-bottom:6px">Options the cashier can pick (tap to switch on or off)</div><div class="chips">${Object.keys(MODS).map(g=>`<button class="chip ${d.mods.includes(g)?'on':''}" aria-pressed="${d.mods.includes(g)}" ${A('dishMod',{g})}>${MODS[g].name}</button>`).join('')}</div></div></div>
  <div class="card pad0"><div style="padding:14px 16px 6px"><h2>2. The recipe for one portion</h2><p class="muted sm">This is what each sale takes off the stock.</p></div>
   <div class="tw">${d.recipe.length?`<table><tr><th>Ingredient</th><th>Amount for one portion</th><th class="r">Cost</th><th></th></tr>${d.recipe.map((r,i)=>{const g=ING(r[0]);return`<tr><td class="b"><label for="md-q${i}">${h(g.name)}</label></td><td><div class="row"><input class="inp narrow ${has('md-q'+i)}" id="md-q${i}" inputmode="decimal" data-m="d.recipe.${i}.1" data-live value="${h(r[1])}"><span class="muted">${h(g.unit)}</span></div></td><td class="r">${rm(Math.round((num(r[1])||0)*g.cost))}</td><td><button class="btn red sm" ${A('dishIngDel',{i})}>Remove</button></td></tr>`}).join('')}<tr><td class="b" colspan="2">Ingredients cost (demo prices)</td><td class="r b">${rm(cost)}</td><td></td></tr></table>`:`<p class="muted" style="padding:6px 16px 12px">No ingredients yet. Without a recipe, selling this dish will not reduce any stock.</p>`}</div>
   <div class="row" style="padding:12px 16px;border-top:1px solid var(--line)"><label class="flabel" for="md-add">Add an ingredient</label><select class="inp" id="md-add" style="width:auto;flex:1;max-width:340px" data-m="d.add" data-r><option value="">Pick an ingredient</option>${ING_CATS.map(c=>`<optgroup label="${c}">${left.filter(x=>x.cat===c).map(x=>`<option value="${x.id}" ${d.add===x.id?'selected':''}>${h(x.name)} (${h(x.unit)})</option>`).join('')}</optgroup>`).join('')}</select><button class="btn sec" ${A('dishIngAdd')} ${d.add?'':'disabled'}>${ic('plus')}Add to recipe</button>${d.add?'':'<span class="muted sm">Pick an ingredient first.</span>'}</div></div>
  <div class="card row"><span class="grow">Food cost at this price ${tip('fc')}</span><b>${np>0?(cost/(np*100)*100).toFixed(0)+'%':'-'}</b></div>
  <div class="foot">${m?`<button class="btn red" id="deldish" ${A('dishDelete',{id:m.id})}>Delete dish</button>`:`<button class="btn sec" ${A('back')}>Cancel</button>`}<div class="rt"><button class="btn big" id="savedish" ${A('dishSave')}>Save dish</button></div></div>`}};
Object.assign(ACT,{
 dishPic:p=>{cur().p.d.e=p.e;render(true)},
 dishMod:p=>{const d=cur().p.d;d.mods=d.mods.includes(p.g)?d.mods.filter(x=>x!==p.g):d.mods.concat(p.g);render(true)},
 dishIngAdd:()=>{const d=cur().p.d;if(!d.add)return;const g=ING(d.add);d.recipe.push([d.add,(g.unit==='piece'||g.unit==='loaf')?'1':'0.1']);d.add='';render(true);toast(g.name+' added to the recipe. Check the amount.')},
 dishIngDel:p=>{const d=cur().p.d,r=d.recipe.splice(p.i,1)[0];render(true);toast(ING(r[0]).name+' removed from the recipe',()=>{d.recipe.splice(p.i,0,r)})},
 dishSave:()=>{const p=cur().p,d=p.d;p.tried=1;const er=dishErrs(d,p.id);if(er.length){render();toast('Not saved yet. Fix the '+plural(er.length,'point')+' in the red box first.');return}
   const cat=d.cat==='__new'?d.newCat.trim():d.cat,vals={name:d.name.trim(),cat,price:Math.round(num(d.price)*100),e:d.e,mods:Object.keys(MODS).filter(g=>d.mods.includes(g)),recipe:d.recipe.map(r=>[r[0],num(r[1])])};
   if(p.id){Object.assign(MENU(p.id),vals);save();stack.pop();render();toast(vals.name+' saved')}
   else{let n=Math.max(600,...S.menu.map(m=>+m.id||0))+1;const m={id:String(n),...vals};S.menu.push(m);IX=null;save();stack.pop();render();toast(vals.name+' is now on the menu (code '+m.id+')',()=>{S.menu=S.menu.filter(x=>x!==m);IX=null})}},
 dishDelete:p=>{const m=MENU(p.id);confirmBox({title:'Delete '+m.name+'?',body:'It will disappear from the till and the menu list. Old receipts and reports keep it. Any bill on the till that already has it stays as it is.',ok:'Yes, delete this dish',no:'No, keep it',danger:true,
   yes:()=>{const i=S.menu.indexOf(m);S.menu.splice(i,1);IX=null;save();stack.pop();render();toast(m.name+' deleted from the menu',()=>{S.menu.splice(i,0,m);IX=null})}})}
});
const LIMITS=[['Pretend (simulated)',['E-invoices are not sent to LHDN MyInvois. The statuses, unique IDs and QR pictures are made up, and nothing is digitally signed.','Payments. Cash, card, DuitNow QR and e-wallet buttons do not move money or talk to any bank or terminal.','Sending orders to suppliers. Nothing is emailed or messaged.','Food Rescue. The partners are invented and nobody is told about an offer.','Staff roles. There are no passwords, anyone can switch role.','Barcode scanning. You search by name or type the item code instead.']],
 ['Estimated or made up',['Every price, cost, weight and sales figure. The 2 months of history are generated by the app.','The kilograms per piece or loaf used to turn waste into kg.','Suggested order amounts. They use minimum stock and the last 14 days of use, which is a rough guide.','The tax rates in Settings are common examples, not advice.']],
 ['What a real product would still need',['A server and database, so data is shared between devices and not stuck in one browser.','Real logins and permissions for each staff member.','MyInvois API registration, a digital certificate for signing, and handling of LHDN\'s real replies and errors.','A licensed payment partner for card, DuitNow QR and e-wallets.','Receipt printer, cash drawer and barcode scanner support.','A way to work when the internet is down and sync later.','Checks by an accountant on tax, rounding and e-invoice rules.','Real interviews and testing with cafe owners. This demo has not been tried by one.']]];
SCREENS.limits={sec:'settings',title:()=>'Limitations',help:['This page is the honest list of what the demo does not really do.','Use it when someone asks "is this real?" during a presentation.','The same list is in the README file.'],
 html(){return `${pageHead('Limitations','What is pretend, what is estimated, and what a real product would still need.')}${LIMITS.map(([t,ls])=>`<div class="card"><h2>${t}</h2><ul style="margin:0;padding-left:20px;display:flex;flex-direction:column;gap:6px">${ls.map(x=>`<li>${x}</li>`).join('')}</ul></div>`).join('')}`}};
