/* ---------- Stock ---------- */
const num=v=>{const n=parseFloat(String(v).replace(',','.'));return isFinite(n)?n:NaN};
function stockStatus(i){const oh=onHand(i.id),bs=batchesOf(i.id),soon=bs.some(b=>daysLeft(b)<=S.settings.expDays);
  if(oh<=0.0005)return pill('Out of stock','bad');if(oh<i.min)return pill('Low','bad');if(soon)return pill('Expiring soon','warn');return pill('OK','ok')}
const expTxt=b=>{const d=daysLeft(b);return d<0?'Expired':d===0?'Today':d===1?'Tomorrow':'In '+d+' days'};
SCREENS.stock={sec:'stock',title:()=>'Stock',help:['Every ingredient is listed with how much is left and when the oldest batch expires.','Tap a row to see its batches, order more, or log waste.','Use the tabs to see only what is low or expiring soon.'],
 html(p){const tab=p.tab||'all',q=(p.q||'').trim().toLowerCase(),low=lowList(),soon=soonList();
  const tabs=`<div class="tabs">${[['all','All items',S.ingredients.length],['low','Low',low.length],['soon','Expiring soon',soon.length]].map(([k,l,n])=>`<button class="tab ${tab===k?'on':''}" ${A('set',{k:'tab',v:k})}>${l} <span class="n">(${n})</span></button>`).join('')}</div>`;
  let body;
  if(tab==='soon'){const bs=soon.filter(b=>!q||ING(b.ing).name.toLowerCase().includes(q));
   body=bs.length?`<table><tr><th>Item</th><th class="r">Amount</th><th>Expires</th><th class="hide-s r">Value</th><th>What to do</th></tr>${bs.map(b=>`<tr><td><button class="btn sec sm" ${A('go',{s:'item',p:{id:b.ing}})}>${h(ING(b.ing).name)}</button></td><td class="r">${qU(b.ing,b.qty)}</td><td>${pill(expTxt(b),daysLeft(b)<=0?'bad':'warn')} <span class="muted sm hide-s">${fDs(b.exp)}</span></td><td class="hide-s r">${rm(Math.round(b.qty*b.cost))}</td>
     <td><div class="row"><button class="btn sec sm" ${A('rescueOffer',{b:b.id})} ${S.rescue.some(r=>r.batch===b.id&&r.status==='Offered')?'disabled':''}>${S.rescue.some(r=>r.batch===b.id&&r.status==='Offered')?'Offered for rescue':'Offer for rescue'}</button><button class="btn red sm" ${A('wasteBatch',{b:b.id})}>Log as waste</button></div></td></tr>`).join('')}</table>`
    :empty(q?'Nothing matches "'+h(q)+'"':'Nothing is expiring in the next '+plural(S.settings.expDays,'day'),q?'':'Good news. Check again tomorrow.',`<button class="btn sec" ${A('set',{k:q?'q':'tab',v:q?'':'all'})}>${q?'Clear search':'See all items'}</button>`)}
  else{let list=(tab==='low'?low:S.ingredients).filter(i=>(!q||i.name.toLowerCase().includes(q))&&(!p.cat||p.cat==='All'||i.cat===p.cat));
   body=list.length?`<table><tr><th>Item</th><th class="r">In stock</th><th class="r hide-s">Minimum${tip('min')}</th><th>Oldest batch expires</th><th class="hide-s">Supplier</th><th>Status</th><th></th></tr>${list.map(i=>{const b=batchesOf(i.id)[0],oo=onOrder(i.id);return`<tr class="click" tabindex="0" ${A('go',{s:'item',p:{id:i.id}})}><td class="b">${h(i.name)}</td><td class="r">${qU(i.id,onHand(i.id))}</td><td class="r hide-s">${qU(i.id,i.min)}</td><td>${b?expTxt(b)+' <span class="muted sm hide-s">'+fDs(b.exp)+'</span>':'-'}</td><td class="hide-s">${h(SUP(i.sup).name.replace(' (demo)',''))}</td><td>${stockStatus(i)}${oo?' '+pill(qf(oo)+' on order','info'):''}</td><td class="chev">Open ›</td></tr>`}).join('')}</table>`
    :empty(q?'No item matches "'+h(q)+'"':'Nothing is below minimum stock',q?'Check the spelling or clear the search.':'Every item has enough on the shelf.',`<button class="btn sec" ${A('set',{k:q?'q':'tab',v:q?'':'all'})}>${q?'Clear search':'See all items'}</button>`)}
  return `${pageHead('Stock','What is on the shelf right now. '+demoTag,`<button class="btn" id="countbtn" ${A('go',{s:'count'})}>Count stock</button><button class="btn sec" ${A('go',{s:'addItem'})}>${ic('plus')}Add item</button>`)}
  ${tabs}<div class="row">${searchBox('q','Search items',p.q)}${tab!=='soon'?`<select class="inp" style="width:auto" data-m="cat" data-r aria-label="Filter by category"><option>All</option>${ING_CATS.map(c=>`<option ${p.cat===c?'selected':''}>${c}</option>`).join('')}</select>`:''}</div>
  <div class="card pad0"><div class="tw">${body}</div></div>`}};
SCREENS.item={sec:'stock',title:p=>ING(p.id).name,help:['The top batch in the list is the oldest, and it is always used first.','"Order more" starts an order to this item\'s supplier with a suggested amount.','"Fix the count" is for when the shelf does not match the app.'],
 html(p){const i=ING(p.id);if(!ix().ing[p.id])return empty('This item is no longer in the list','',`<button class="btn" ${A('root',{s:'stock'})}>Back to Stock</button>`);
  const bs=batchesOf(i.id),oh=onHand(i.id),oo=onOrder(i.id),avg=avgUse(i.id),ws=S.waste.filter(w=>w.ing===i.id).slice(-6).reverse(),used=S.menu.filter(m=>m.recipe.some(r=>r[0]===i.id));
  return `${pageHead(h(i.name),`${stockStatus(i)} ${h(i.cat)} · from ${h(SUP(i.sup).name)}`,`<button class="btn" ${A('go',{s:'newOrder',p:{ing:i.id}})}>Order more</button><button class="btn sec" ${A('root',{s:'waste',p:{ing:i.id}})}>Log waste</button><button class="btn sec" ${A('adjust',{id:i.id})}>Fix the count</button><button class="btn sec" ${A('editItem',{id:i.id})}>Edit item</button>`)}
  <div class="grid g4"><div class="kpi"><span class="l">In stock</span><span class="v">${qU(i.id,oh)}</span><span class="s">Minimum ${qU(i.id,i.min)}</span></div><div class="kpi"><span class="l">On order</span><span class="v">${qU(i.id,oo)}</span><span class="s">Not delivered yet</span></div>
   <div class="kpi"><span class="l">Used per day</span><span class="v">${qf(avg)} ${h(i.unit)}</span><span class="s">Average of the last 14 days</span></div><div class="kpi"><span class="l">Will last about</span><span class="v">${avg>0.001?plural(Math.floor(oh/avg),'day'):'-'}</span><span class="s">At the current pace</span></div></div>
  <div class="card pad0"><div style="padding:14px 16px 6px"><h2>Batches ${tip('fefo')}</h2><p class="muted sm">Use oldest first: the top row is used before the others.</p></div><div class="tw">${bs.length?`<table><tr><th>Received</th><th>Expires</th><th class="r">Amount left</th><th class="r">Cost per ${h(i.unit)}</th><th>What to do</th></tr>${bs.map(b=>`<tr><td>${fD(b.recv)}</td><td>${fD(b.exp)} ${pill(expTxt(b),daysLeft(b)<=S.settings.expDays?'warn':'ok')}</td><td class="r">${qU(i.id,b.qty)}</td><td class="r">${rm(b.cost)}</td><td><button class="btn red sm" ${A('wasteBatch',{b:b.id})}>Log as waste</button></td></tr>`).join('')}</table>`:empty('Nothing in stock','Order more, or receive a delivery.',`<button class="btn" ${A('go',{s:'newOrder',p:{ing:i.id}})}>Order more</button>`)}</div></div>
  <div class="grid g2"><div class="card"><h2>Recent waste</h2>${ws.length?ws.map(w=>`<div class="tot sm" style="padding:5px 0"><span>${fDs(w.dt)} · ${h(w.reason)}</span><span>${qU(i.id,w.qty)} · ${rm(w.cost)}</span></div>`).join('')+`<div style="margin-top:10px"><button class="btn sec sm" ${A('go',{s:'wasteItem',p:{ing:i.id}})}>See all waste for this item</button></div>`:'<p class="muted">No waste logged for this item.</p>'}</div>
   <div class="card"><h2>Used in these menu items</h2>${used.length?`<p>${used.map(m=>h(m.name)).join(', ')}</p><p class="muted sm" style="margin-top:6px">Each sale of these takes this ingredient off the stock automatically.</p>`:'<p class="muted">Not used in any recipe yet.</p>'}</div></div>`}};
Object.assign(ACT,{
 adjust:p=>{const i=ING(p.id);modal(M=>{const v=num(M.v),bad=!(v>=0);return`${mHead('Fix the count: '+h(i.name))}<p>The app thinks there is <b>${qU(i.id,onHand(i.id))}</b>. Count what is really on the shelf and type it here.</p>${field('adjv','Counted amount ('+h(i.unit)+')',inp('adjv','v',M.v,{attr:'inputmode="decimal" data-live data-enter="adjustDo"',cls:bad?'err':''}))}
   <div class="mf">${bad?'<span class="why">Type a number that is 0 or more.</span>':''}<button class="btn sec" ${A('closeModal')}>Cancel</button><button class="btn" ${A('adjustDo')} ${bad?'disabled':''}>Save the new count</button></div>`},{id:i.id,v:String(onHand(i.id))})},
 adjustDo:()=>{const v=num(M.v);if(!(v>=0))return;const id=M.id,snap=JSON.stringify(S.batches),d=adjustStock(id,v);closeModal();save();render(true);toast(d?ING(id).name+' count changed by '+(d>0?'+':'')+qf(d)+' '+ING(id).unit:'No change. The count already matched.',d?()=>{S.batches=JSON.parse(snap)}:null)},
 editItem:p=>{const i=ING(p.id);modal(M=>`${mHead('Edit '+h(i.name))}<div class="fgrid">${field('ei-n','Name',inp('ei-n','name',M.name))}${field('ei-m','Minimum stock ('+h(i.unit)+')',inp('ei-m','min',M.min,{attr:'inputmode="decimal"'}),'min')}${field('ei-c','Usual price per '+h(i.unit)+' (RM)',inp('ei-c','cost',M.cost,{attr:'inputmode="decimal"'}))}${field('ei-s','Keeps for (days)',inp('ei-s','shelf',M.shelf,{attr:'inputmode="numeric"'}))}</div>
   <div class="mf"><button class="btn sec" ${A('closeModal')}>Cancel</button><button class="btn" ${A('editItemDo')}>Save changes</button></div>`,{id:i.id,name:i.name,min:String(i.min),cost:amt(i.cost),shelf:String(i.shelf)})},
 editItemDo:()=>{const i=ING(M.id),mn=num(M.min),c=num(M.cost),sh=num(M.shelf);if(!M.name.trim()||!(mn>=0)||!(c>=0)||!(sh>=1)){toast('Check the form: the name cannot be empty and the numbers must be 0 or more.');return}
   i.name=M.name.trim();i.min=mn;i.cost=Math.round(c*100);i.shelf=Math.round(sh);closeModal();save();render(true);toast('Saved changes to '+i.name)},
 wasteBatch:p=>{const b=S.batches.find(x=>x.id===p.b);if(!b)return;const i=ING(b.ing);confirmBox({title:'Log this batch as waste?',body:`<b>${qU(i.id,b.qty)}</b> of ${h(i.name)} (worth ${rm(Math.round(b.qty*b.cost))}) will leave the stock and go into the waste log as "${daysLeft(b)<=0?'Expired':'Spoiled'}".`,ok:'Yes, log as waste',danger:true,
   yes:()=>{const w=logWaste(i.id,b.qty,daysLeft(b)<=0?'Expired':'Spoiled',{batch:b.id});save();render(true);toast(i.name+' logged as waste',()=>undoWaste(w.id))}})}
});
SCREENS.count={sec:'stock',title:()=>'Count stock',help:['Walk the shelves and type what you really have next to each item.','Leave a box as it is when the amount is right.','Press "Save count" at the bottom when you are done. Only the boxes you changed are updated.'],
 html(p){p.vals=p.vals||{};const cat=p.cat||ING_CATS[0],list=S.ingredients.filter(i=>i.cat===cat),ch=Object.keys(p.vals).filter(k=>{const v=num(p.vals[k]);return v>=0&&Math.abs(v-onHand(k))>0.0005}),bad=Object.keys(p.vals).filter(k=>!(num(p.vals[k])>=0));
  return `${pageHead('Count stock','Type what is really on the shelf. Go through each group, then save once.')}
  <div class="tabs">${ING_CATS.map(c=>`<button class="tab ${cat===c?'on':''}" ${A('set',{k:'cat',v:c})}>${c}</button>`).join('')}</div>
  <div class="card pad0"><div class="tw"><table><tr><th>Item</th><th class="r">App says</th><th>You counted</th></tr>${list.map(i=>{const v=p.vals[i.id],b=v!=null&&!(num(v)>=0);return`<tr><td class="b"><label for="c-${i.id}">${h(i.name)}</label></td><td class="r">${qU(i.id,onHand(i.id))}</td><td><div class="row"><input class="inp narrow ${b?'err':''}" id="c-${i.id}" inputmode="decimal" data-m="vals.${i.id}" data-live value="${h(v!=null?v:qf(onHand(i.id)))}"><span class="muted">${h(i.unit)}</span>${b?'<span class="why">Numbers only</span>':''}</div></td></tr>`}).join('')}</table></div></div>
  <div class="foot"><button class="btn sec" ${A('back')}>Cancel</button><div class="rt"><span class="${bad.length?'why':'muted sm'}">${bad.length?'Fix the boxes marked in red first.':ch.length?plural(ch.length,'item')+' changed':'Nothing changed yet'}</span><button class="btn big" id="savecount" ${A('countSave')} ${bad.length?'disabled':''}>Save count</button></div></div>`}};
ACT.countSave=()=>{const p=cur().p,diffs=[];Object.keys(p.vals||{}).forEach(k=>{const v=num(p.vals[k]);if(v>=0){const d=adjustStock(k,v);if(d)diffs.push([k,d])}});save();go('countDone',{diffs},true)};
SCREENS.countDone={sec:'stock',title:()=>'Count saved',html(p){return`<div class="card donebox"><span class="tick">${ic('check')}</span><h1>Stock count saved</h1><p>${p.diffs.length?plural(p.diffs.length,'item')+' updated.':'Everything already matched. Nothing was changed.'}</p>
  ${p.diffs.length?`<div class="tw" style="width:100%;max-width:460px"><table>${p.diffs.map(([k,d])=>`<tr><td style="text-align:left">${h(ING(k).name)}</td><td class="r ${d<0?'red-t':'grn-t'} b">${d>0?'+':''}${qf(d)} ${h(ING(k).unit)}</td></tr>`).join('')}</table></div>`:''}
  <div class="acts"><button class="btn big" ${A('root',{s:'stock'})}>Back to Stock</button><button class="btn sec big" ${A('root',{s:'home'})}>Back to Home</button></div></div>`}};
SCREENS.addItem={sec:'stock',title:()=>'Add item',help:['Fill in the name and how you measure it (kg, L, piece).','Minimum stock is the lowest amount you want on the shelf.','Press "Save item". You can then receive a delivery or fix the count to add stock.'],
 html(p){if(!p.init){Object.assign(p,{init:1,name:'',unit:'kg',cat:ING_CATS[0],sup:S.suppliers[0].id,cost:'',min:'',shelf:'7'})}
  const errs=p.tried?addItemErrs(p):[];
  return `${pageHead('Add item','A new ingredient or supply to keep track of.')}${errs.length?`<div class="errs" role="alert">${errs.map(e=>`<div class="e"><span>${e[1]}</span><button class="btn sec sm" ${A('focus',{id:e[0]})}>Fix it</button></div>`).join('')}</div>`:''}
  <div class="card"><div class="fgrid">${field('ai-n','Item name',inp('ai-n','name',p.name,{ph:'For example: Oat milk'}))}
   ${field('ai-u','Measured in',`<select class="inp" id="ai-u" data-m="unit">${['kg','L','piece','loaf'].map(u=>`<option ${p.unit===u?'selected':''}>${u}</option>`).join('')}</select>`)}
   ${field('ai-c','Group',`<select class="inp" id="ai-c" data-m="cat">${ING_CATS.map(u=>`<option ${p.cat===u?'selected':''}>${u}</option>`).join('')}</select>`)}
   ${field('ai-s','Supplier',`<select class="inp" id="ai-s" data-m="sup">${S.suppliers.map(u=>`<option value="${u.id}" ${p.sup===u.id?'selected':''}>${h(u.name)}</option>`).join('')}</select>`)}
   ${field('ai-p','Usual price per unit (RM)',inp('ai-p','cost',p.cost,{attr:'inputmode="decimal"',ph:'0.00'}))}${field('ai-m','Minimum stock',inp('ai-m','min',p.min,{attr:'inputmode="decimal"',ph:'For example: 2'}),'min')}${field('ai-d','Keeps for (days)',inp('ai-d','shelf',p.shelf,{attr:'inputmode="numeric"'}))}</div></div>
  <div class="foot"><button class="btn sec" ${A('back')}>Cancel</button><div class="rt"><button class="btn big" ${A('addItemSave')}>Save item</button></div></div>`}};
function addItemErrs(p){const e=[];if(!p.name.trim())e.push(['ai-n','Item name is missing.']);if(!(num(p.cost)>=0))e.push(['ai-p','Price is missing. Type a number, for example 7.50.']);if(!(num(p.min)>=0))e.push(['ai-m','Minimum stock is missing. Type a number, for example 2.']);if(!(num(p.shelf)>=1))e.push(['ai-d','"Keeps for" must be 1 day or more.']);return e}
ACT.addItemSave=()=>{const p=cur().p;p.tried=1;if(addItemErrs(p).length){render();toast('Not saved yet. Fix the '+plural(addItemErrs(p).length,'point')+' in the red box first.');return}const id='x'+S.seq.id++;S.ingredients.push({id,name:p.name.trim(),unit:p.unit,cat:p.cat,sup:p.sup,cost:Math.round(num(p.cost)*100),min:num(p.min),shelf:Math.round(num(p.shelf)),kg:p.unit==='piece'?0.1:p.unit==='loaf'?0.6:1});IX=null;save();stack.pop();go('item',{id});toast(p.name.trim()+' added. It has no stock yet.')};

/* ---------- Orders to suppliers ---------- */
const OST={sent:['Sent, waiting for delivery','info'],part:['Part received','warn'],received:['Received','ok'],cancelled:['Cancelled','bad']};
const ordVal=o=>o.lines.reduce((a,l)=>a+Math.round(l.qty*l.price),0);
const ordBy=id=>S.orders.find(o=>o.id===id);
const billPay=b=>b.paid?pill('Paid','ok'):b.due<today()?pill('Overdue','bad'):pill('Not paid yet','warn');
const einvPill=s=>s==='Valid'?pill('E-invoice received','ok'):pill('No e-invoice yet','warn');
SCREENS.orders={sec:'orders',title:()=>'Orders',help:['This is where you order from suppliers and take in deliveries.','"Suggested" lists what is running low. One button turns it into an order.','Tap any row to open it. The green button on each order shows the next step.'],
 html(p){const tab=p.tab||'orders',sg=suggestions(),open=S.orders.filter(o=>o.status==='sent'||o.status==='part');
  const tabs=`<div class="tabs">${[['orders','Orders',S.orders.length],['suggest','Suggested',sg.length],['suppliers','Suppliers',S.suppliers.length],['bills','Supplier bills',S.bills.length]].map(([k,l,n])=>`<button class="tab ${tab===k?'on':''}" ${A('set',{k:'tab',v:k})}>${l} <span class="n">(${n})</span></button>`).join('')}</div>`;
  let body='',acts=`<button class="btn" id="neworder" ${A('go',{s:'newOrder'})}>${ic('plus')}Create order</button><button class="btn sec" ${A('go',{s:'receive',p:{step:0}})}>Receive delivery</button>`;
  if(tab==='orders'){const q=(p.q||'').trim().toLowerCase(),rows=S.orders.slice().sort((a,b)=>b.no-a.no).filter(o=>!q||String(o.no).includes(q)||SUP(o.sup).name.toLowerCase().includes(q));
   body=`<div class="row">${searchBox('q','Search by supplier or order number',p.q)}</div><div class="card pad0"><div class="tw">${rows.length?`<table><tr><th>Order</th><th>Supplier</th><th class="hide-s">Sent</th><th>Expected</th><th class="r hide-s">Value</th><th>Status</th><th></th></tr>${rows.map(o=>`<tr class="click" tabindex="0" ${A('go',{s:'order',p:{id:o.id}})}><td class="b">#${o.no}</td><td>${h(SUP(o.sup).name)}</td><td class="hide-s">${fDs(o.date)}</td><td>${fDs(o.expected)}</td><td class="r hide-s">${rm(ordVal(o))}</td><td>${pill(...OST[o.status])}</td><td class="chev">Open ›</td></tr>`).join('')}</table>`
     :empty(q?'No order matches "'+h(q)+'"':'No orders yet',q?'':'Orders you send to suppliers show up here.',q?`<button class="btn sec" ${A('set',{k:'q',v:''})}>Clear search</button>`:`<button class="btn" ${A('go',{s:'newOrder'})}>Create your first order</button>`)}</div></div>`}
  else if(tab==='suggest'){const by={};sg.forEach(x=>{(by[ING(x.ing).sup]=by[ING(x.ing).sup]||[]).push(x)});
   body=sg.length?`<p class="muted">Worked out from minimum stock and how much was used in the last 14 days. You can change the amounts before sending.</p><div class="grid g2">${Object.keys(by).map(s=>`<div class="card" style="display:flex;flex-direction:column;gap:10px"><h2>${h(SUP(s).name)}</h2>${by[s].map(x=>`<div class="tot sm"><span>${h(ING(x.ing).name)} <span class="muted">(${qU(x.ing,x.oh)} left)</span></span><b>${qU(x.ing,x.qty)}</b></div>`).join('')}
     <button class="btn" style="margin-top:auto" ${A('go',{s:'newOrder',p:{sup:s,all:1}})}>Turn into an order (${plural(by[s].length,'item')})</button></div>`).join('')}</div>`
    :`<div class="card">${empty('Nothing needs ordering right now','Every item is above its minimum stock or already on order.',`<button class="btn sec" ${A('go',{s:'newOrder'})}>Create an order anyway</button>`)}</div>`}
  else if(tab==='suppliers'){acts=`<button class="btn" ${A('supForm',{})}>${ic('plus')}Add supplier</button>`;
   body=`<div class="card pad0"><div class="tw"><table><tr><th>Supplier</th><th class="hide-s">Phone</th><th>Delivers in</th><th class="r">Items</th><th></th></tr>${S.suppliers.map(s=>`<tr class="click" tabindex="0" ${A('go',{s:'supplier',p:{id:s.id}})}><td class="b">${h(s.name)}</td><td class="hide-s">${h(s.phone)}</td><td>${plural(s.lead,'day')}</td><td class="r">${S.ingredients.filter(i=>i.sup===s.id).length}</td><td class="chev">Open ›</td></tr>`).join('')}</table></div></div>`}
  else{acts=`<button class="btn" ${A('go',{s:'billForm'})}>${ic('plus')}Enter supplier bill</button>`;const rows=S.bills.slice().sort((a,b)=>a.date<b.date?1:-1);
   body=`<div class="card pad0"><div class="tw">${rows.length?`<table><tr><th>Bill</th><th>Supplier</th><th class="hide-s">Date</th><th>Pay by</th><th class="r">Amount</th><th>Payment</th><th class="hide-s">E-invoice${tip('einv')}</th><th></th></tr>${rows.map(b=>`<tr class="click" tabindex="0" ${A('go',{s:'bill',p:{id:b.id}})}><td class="b">${h(b.no)}</td><td>${h(SUP(b.sup).name)}</td><td class="hide-s">${fDs(b.date)}</td><td>${fDs(b.due)}</td><td class="r">${rm(b.amount)}</td><td>${billPay(b)}</td><td class="hide-s">${einvPill(b.einv)}</td><td class="chev">Open ›</td></tr>`).join('')}</table>`:empty('No supplier bills yet','When a supplier sends a bill, enter it here to keep track of what you owe.',`<button class="btn" ${A('go',{s:'billForm'})}>Enter the first bill</button>`)}</div></div>`}
  return `${pageHead('Orders',open.length?plural(open.length,'order')+' waiting for delivery. '+demoTag:'Order from suppliers and take in deliveries. '+demoTag,acts)}${tabs}${body}`}};
SCREENS.newOrder={sec:'orders',title:()=>'New order',help:['Step 1: pick the supplier. Step 2: set how much of each item you want. Step 3: check and send.','Items that are running low are already filled in with a suggested amount.','Nothing is really sent in this demo.'],
 html(p){if(!p.init){p.init=1;p.qty=p.qty||{};p.step=1;const sg=suggestions();
    if(p.ing){p.sup=ING(p.ing).sup;const x=sg.find(y=>y.ing===p.ing),i=ING(p.ing);p.qty[p.ing]=String(x?x.qty:Math.max(1,Math.ceil(i.min)));p.step=2}
    else if(p.sup){sg.filter(x=>ING(x.ing).sup===p.sup).forEach(x=>p.qty[x.ing]=String(x.qty));p.step=2}}
  const sg=suggestions(),steps=stepsBar(['Pick supplier','Add items','Check and send'],p.step-1);
  if(p.step===1)return `${pageHead('New order','Who are you ordering from?')}${steps}<div class="grid g2">${S.suppliers.map(s=>{const n=sg.filter(x=>ING(x.ing).sup===s.id).length;return`<button class="alert" ${A('ordSup',{s:s.id})}><span class="ai" style="background:var(--green-s);color:var(--green-d)">${ic('truck')}</span><span class="grow" style="text-align:left">${h(s.name)}<small>Delivers in ${plural(s.lead,'day')}${n?' · '+plural(n,'item')+' running low':''}</small></span><span class="go">Pick${ic('chev')}</span></button>`}).join('')}</div>
   <div class="foot"><button class="btn sec" ${A('back')}>Cancel</button></div>`;
  const sup=SUP(p.sup),items=S.ingredients.filter(i=>i.sup===p.sup),q=(p.q||'').trim().toLowerCase();
  const lines=items.map(i=>({i,q:num(p.qty[i.id])})).filter(x=>x.q>0),total=lines.reduce((a,x)=>a+Math.round(x.q*x.i.cost),0);
  if(p.step===2)return `${pageHead('Order from '+h(sup.name),'Set how much you want. Suggested amounts are filled in for items that are low.')}${steps}
   <div class="row">${searchBox('q','Search this supplier\'s items',p.q)}</div>
   <div class="card pad0"><div class="tw"><table><tr><th>Item</th><th class="r hide-s">In stock</th><th>Order how much</th><th class="r hide-s">Price</th><th class="r">Line total</th></tr>${items.filter(i=>!q||i.name.toLowerCase().includes(q)).map(i=>{const v=p.qty[i.id]||'',n=num(v),s=sg.find(x=>x.ing===i.id);return`<tr><td><label class="b" for="oq-${i.id}">${h(i.name)}</label> ${isLow(i)?pill('Low','bad'):''}${s&&!(n>0)?` <button class="btn sec sm" ${A('ordQty',{i:i.id,v:s.qty})}>Add suggested ${qf(s.qty)}</button>`:''}</td><td class="r hide-s">${qU(i.id,onHand(i.id))}</td>
     <td><div class="stepper"><button ${A('ordStep',{i:i.id,d:-1})} aria-label="Less ${h(i.name)}" ${n>0?'':'disabled'}>−</button><input class="inp" id="oq-${i.id}" inputmode="decimal" data-m="qty.${i.id}" data-live value="${h(v)}" placeholder="0"><button ${A('ordStep',{i:i.id,d:1})} aria-label="More ${h(i.name)}">+</button><span class="muted sm">${h(i.unit)}</span></div></td><td class="r hide-s">${rm(i.cost)}</td><td class="r b">${n>0?rm(Math.round(n*i.cost)):'-'}</td></tr>`}).join('')}</table></div></div>
   <div class="foot"><button class="btn sec" ${A('set',{k:'step',v:1})}>${ic('back')}Change supplier</button><div class="rt">${lines.length?`<span class="b num">${plural(lines.length,'item')} · ${rm(total)}</span>`:'<span class="why">Add at least 1 item first.</span>'}<button class="btn big" id="ordreview" ${A('set',{k:'step',v:3})} ${lines.length?'':'disabled'}>Save and check the order</button></div></div>`;
  return `${pageHead('Check and send','Order to '+h(sup.name)+'. Expected '+fD(addDays(today(),sup.lead))+'.')}${steps}
   <div class="card pad0"><div class="tw"><table><tr><th>Item</th><th class="r">Amount</th><th class="r">Price</th><th class="r">Line total</th></tr>${lines.map(x=>`<tr><td class="b">${h(x.i.name)}</td><td class="r">${qU(x.i.id,x.q)}</td><td class="r">${rm(x.i.cost)}</td><td class="r">${rm(Math.round(x.q*x.i.cost))}</td></tr>`).join('')}<tr><td colspan="3" class="r b">Order total (demo prices)</td><td class="r b">${rm(total)}</td></tr></table></div></div>
   <p class="muted sm">This is a demo. Pressing the button saves the order here but does not email or message the supplier.</p>
   <div class="foot"><button class="btn sec" ${A('set',{k:'step',v:2})}>${ic('back')}Change items</button><div class="rt"><button class="btn big" id="ordsend" ${A('ordSend')}>Send order to ${h(sup.name.replace(' (demo)',''))}</button></div></div>`}};
Object.assign(ACT,{
 ordSup:p=>{const c=cur().p;if(c.sup!==p.s){c.qty={};suggestions().filter(x=>ING(x.ing).sup===p.s).forEach(x=>c.qty[x.ing]=String(x.qty))}c.sup=p.s;c.step=2;c.q='';render()},
 ordStep:p=>{const c=cur().p,i=ING(p.i),st=(i.unit==='piece'||i.unit==='loaf')?1:0.5,v=Math.max(0,(num(c.qty[p.i])||0)+p.d*st);c.qty[p.i]=v?qf(v):'';render(true)},
 ordQty:p=>{cur().p.qty[p.i]=String(p.v);render(true)},
 ordSend:()=>{const c=cur().p,sup=SUP(c.sup),lines=S.ingredients.filter(i=>i.sup===c.sup&&num(c.qty[i.id])>0).map(i=>({ing:i.id,qty:num(c.qty[i.id]),price:i.cost,recv:0}));if(!lines.length)return;
   const o={id:uid('o'),no:S.seq.order++,sup:c.sup,date:today(),expected:addDays(today(),sup.lead),status:'sent',lines};S.orders.push(o);save();go('orderDone',{id:o.id},true);toast('Order sent to '+sup.name,()=>{S.orders=S.orders.filter(x=>x!==o);root('orders')})}
});
SCREENS.orderDone={sec:'orders',title:()=>'Order sent',html(p){const o=ordBy(p.id);if(!o)return empty('This order was removed','',`<button class="btn" ${A('root',{s:'orders'})}>Back to Orders</button>`);return`${stepsBar(['Pick supplier','Add items','Check and send'],3)}<div class="card donebox"><span class="tick">${ic('check')}</span><h1>Order #${o.no} sent</h1><p>To ${h(SUP(o.sup).name)} · ${plural(o.lines.length,'item')} · ${rm(ordVal(o))}</p><p class="muted">Expected on ${fD(o.expected)}. When it arrives, open the order and press "Receive goods". (Demo: nothing was really sent.)</p>
  <div class="acts"><button class="btn big" ${A('root',{s:'orders'})}>Back to Orders</button><button class="btn sec big" ${A('root',{s:'home'})}>Back to Home</button></div><div class="acts"><button class="btn sec sm" ${A('go',{s:'order',p:{id:o.id}})}>Open this order</button></div></div>`}};
SCREENS.order={sec:'orders',title:p=>{const o=ordBy(p.id);return o?'Order #'+o.no:'Order'},help:['This shows what was ordered and what has arrived so far.','When the delivery comes, press the green "Receive goods" button.','If the supplier will not deliver the rest, press "Close order".'],
 html(p){const o=ordBy(p.id);if(!o)return empty('This order was removed','',`<button class="btn" ${A('root',{s:'orders'})}>Back to Orders</button>`);const b=S.bills.find(x=>x.order===o.id),open=o.status==='sent'||o.status==='part';
  const acts=open?`<button class="btn" id="recvbtn" ${A('go',{s:'receive',p:{order:o.id,step:1}})}>Receive goods</button>`+(o.status==='sent'?`<button class="btn red" ${A('ordCancel',{id:o.id})}>Cancel order</button>`:`<button class="btn sec" ${A('ordClose',{id:o.id})}>Close order (the rest is not coming)</button>`)
   :o.status==='received'?(b?`<button class="btn" ${A('go',{s:'bill',p:{id:b.id}})}>Open the supplier bill</button>`:`<button class="btn" ${A('go',{s:'billForm',p:{order:o.id}})}>Enter the supplier bill</button>`):`<button class="btn" ${A('go',{s:'newOrder',p:{sup:o.sup}})}>Order from this supplier again</button>`;
  return `${pageHead('Order #'+o.no,`${pill(...OST[o.status])} ${h(SUP(o.sup).name)} · sent ${fD(o.date)} · expected ${fD(o.expected)}`,acts)}
  <div class="card pad0"><div class="tw"><table><tr><th>Item</th><th class="r">Ordered</th><th class="r">Received</th><th class="r hide-s">Price</th><th class="r">Line total</th></tr>${o.lines.map(l=>`<tr class="click" tabindex="0" ${A('go',{s:'item',p:{id:l.ing}})}><td class="b">${h(ING(l.ing).name)}</td><td class="r">${qU(l.ing,l.qty)}</td><td class="r">${qU(l.ing,l.recv)} ${l.recv>=l.qty?pill('All in','ok'):l.recv>0?pill('Part','warn'):''}</td><td class="r hide-s">${rm(l.price)}</td><td class="r">${rm(Math.round(l.qty*l.price))}</td></tr>`).join('')}<tr><td colspan="4" class="r b hide-s">Order total</td><td class="r b">${rm(ordVal(o))}</td></tr></table></div></div><p class="muted sm">Tap an item to see its stock.</p>`}};
ACT.ordCancel=p=>{const o=ordBy(p.id);confirmBox({title:'Cancel order #'+o.no+'?',body:'The order to '+h(SUP(o.sup).name)+' will be marked as cancelled and nothing will be expected. In real life you would also need to tell the supplier.',ok:'Yes, cancel the order',no:'No, keep it',danger:true,yes:()=>{o.status='cancelled';save();render();toast('Order #'+o.no+' cancelled',()=>{o.status='sent'})}})};
ACT.ordClose=p=>{const o=ordBy(p.id);confirmBox({title:'Close order #'+o.no+'?',body:'The items that have not arrived will no longer be expected. Stock already received stays as it is.',ok:'Yes, close the order',yes:()=>{o.status='received';o.closedShort=true;save();render();toast('Order #'+o.no+' closed',()=>{o.status='part';o.closedShort=false})}})};
const RSTEPS=['Pick order','Check items','Confirm'];
SCREENS.receive={sec:'orders',title:()=>'Receive goods',help:['Step 1: pick the order that arrived. Step 2: check the amount, expiry date and price of each item. Step 3: confirm.','If only part of the order came, type the amount that really arrived. The rest stays "on order".','Each item becomes a new batch in stock with its own expiry date.'],
 html(p){const open=S.orders.filter(o=>o.status==='sent'||o.status==='part').sort((a,b)=>a.expected<b.expected?-1:1);
  if(!p.order||!p.step){return `${pageHead('Receive goods','Which delivery arrived?')}${stepsBar(RSTEPS,0)}${open.length?`<div class="grid">${open.map(o=>`<button class="alert" ${A('recvPick',{id:o.id})}><span class="ai" style="background:var(--blue-s);color:var(--blue)">${ic('truck')}</span><span class="grow" style="text-align:left">Order #${o.no} · ${h(SUP(o.sup).name)}<small>${plural(o.lines.filter(l=>l.recv<l.qty).length,'item')} still to come · expected ${fDs(o.expected)}${o.status==='part'?' · part received':''}</small></span><span class="go">This one${ic('chev')}</span></button>`).join('')}</div>`
    :`<div class="card">${empty('No deliveries are expected','Goods are received against an order. Create an order first.',`<button class="btn" ${A('go',{s:'newOrder'})}>Create an order</button>`)}</div>`}<div class="foot"><button class="btn sec" ${A('back')}>Cancel</button></div>`}
  const o=ordBy(p.order);if(!o)return empty('This order was removed','',`<button class="btn" ${A('root',{s:'orders'})}>Back to Orders</button>`);
  if(!p.rows){p.rows={};o.lines.forEach((l,i)=>{const rem=r3(l.qty-l.recv);if(rem>0)p.rows[i]={qty:qf(rem),exp:addDays(today(),ING(l.ing).shelf),price:amt(l.price)}})}
  const errs=recvErrs(p,o),idx=Object.keys(p.rows),got=idx.filter(i=>num(p.rows[i].qty)>0);
  if(p.step===1)return `${pageHead('Check the items','Order #'+o.no+' from '+h(SUP(o.sup).name)+'. Change anything that is different from what arrived.')}${stepsBar(RSTEPS,1)}
   ${p.tried&&errs.length?`<div class="errs" role="alert">${errs.map(e=>`<div class="e"><span>${e[1]}</span><button class="btn sec sm" ${A('focus',{id:e[0]})}>Fix it</button></div>`).join('')}</div>`:''}
   <div class="grid">${idx.map(i=>{const l=o.lines[i],r=p.rows[i],g=ING(l.ing);return`<div class="card"><div class="row" style="margin-bottom:10px"><h3 class="grow">${h(g.name)}</h3><span class="muted sm">Waiting for ${qU(l.ing,r3(l.qty-l.recv))}</span></div><div class="fgrid">
     ${field('rq-'+i,'Amount received ('+h(g.unit)+')',inp('rq-'+i,'rows.'+i+'.qty',r.qty,{attr:'inputmode="decimal"'}))}${field('re-'+i,'Expiry date on the pack',inp('re-'+i,'rows.'+i+'.exp',r.exp,{type:'date'}))}${field('rp-'+i,'Price per '+h(g.unit)+' (RM)',inp('rp-'+i,'rows.'+i+'.price',r.price,{attr:'inputmode="decimal"'}))}</div></div>`}).join('')}</div>
   <div class="foot"><button class="btn sec" ${A('set',{k:'step',v:0})}>${ic('back')}Pick another order</button><div class="rt"><button class="btn big" id="recvnext" ${A('recvNext')}>Save and go to Confirm</button></div></div>`;
  return `${pageHead('Confirm goods received','Order #'+o.no+' from '+h(SUP(o.sup).name))}${stepsBar(RSTEPS,2)}
   <div class="card pad0"><div class="tw"><table><tr><th>Item</th><th class="r">Received now</th><th>Expires</th><th class="r">Price</th></tr>${got.map(i=>{const l=o.lines[i],r=p.rows[i];return`<tr><td class="b">${h(ING(l.ing).name)}</td><td class="r">${qU(l.ing,num(r.qty))} ${num(r.qty)<r3(l.qty-l.recv)?pill('Part','warn'):''}</td><td>${fD(r.exp)}</td><td class="r">${rm(Math.round(num(r.price)*100))}</td></tr>`}).join('')}</table></div></div>
   ${idx.length>got.length?`<p class="muted">${plural(idx.length-got.length,'item')} did not arrive and will stay "on order".</p>`:''}
   <div class="foot"><button class="btn sec" ${A('set',{k:'step',v:1})}>${ic('back')}Change something</button><div class="rt"><button class="btn big" id="recvdo" ${A('recvDo')}>Confirm goods received</button></div></div>`}};
function recvErrs(p,o){const e=[];Object.keys(p.rows).forEach(i=>{const r=p.rows[i],n=ING(o.lines[i].ing).name,q=num(r.qty);
  if(!(q>=0))e.push(['rq-'+i,n+': the amount must be a number. Type 0 if none arrived.']);
  if(q>0&&(!/^\d{4}-\d{2}-\d{2}$/.test(r.exp||'')))e.push(['re-'+i,n+': pick the expiry date printed on the pack.']);else if(q>0&&r.exp<today())e.push(['re-'+i,n+': the expiry date is in the past. Check the date, or do not accept this item.']);
  if(q>0&&!(num(r.price)>=0))e.push(['rp-'+i,n+': the price must be a number, for example 7.50.'])});
  if(!e.length&&!Object.keys(p.rows).some(i=>num(p.rows[i].qty)>0))e.push(['rq-'+Object.keys(p.rows)[0],'Nothing is marked as received. Type the amount that arrived for at least 1 item.']);return e}
Object.assign(ACT,{
 recvPick:p=>{const c=cur().p;c.order=p.id;c.step=1;c.rows=null;c.tried=0;render()},
 recvNext:()=>{const c=cur().p,o=ordBy(c.order);c.tried=1;if(recvErrs(c,o).length){render();toast('Fix the '+plural(recvErrs(c,o).length,'point')+' in the red box first.');return}c.step=2;render()},
 recvDo:()=>{const c=cur().p,o=ordBy(c.order),made=[];Object.keys(c.rows).forEach(i=>{const r=c.rows[i],q=num(r.qty);if(q>0){const l=o.lines[i];l.recv=r3(l.recv+q);const pr=Math.round(num(r.price)*100);made.push(addBatch(l.ing,q,r.exp,pr).id)}});
   o.status=o.lines.every(l=>l.recv>=l.qty)?'received':'part';save();go('receiveDone',{id:o.id,made},true)}
});
SCREENS.receiveDone={sec:'orders',title:()=>'Goods received',html(p){const o=ordBy(p.id),bs=S.batches.filter(b=>p.made.includes(b.id));return`${stepsBar(RSTEPS,3)}<div class="card donebox"><span class="tick">${ic('check')}</span><h1>Stock updated</h1><p>${plural(bs.length,'new batch','new batches')} added from order #${o.no}. ${o.status==='part'?'The order stays open for the items that did not arrive.':'The order is now complete.'}</p>
  <div class="tw" style="width:100%;max-width:480px"><table>${bs.map(b=>`<tr><td style="text-align:left">${h(ING(b.ing).name)}</td><td class="r b grn-t">+${qU(b.ing,b.qty)}</td><td class="r muted">now ${qU(b.ing,onHand(b.ing))}</td></tr>`).join('')}</table></div>
  <div class="acts"><button class="btn big" ${A('root',{s:'home'})}>Back to Home</button>${S.bills.some(x=>x.order===o.id)?'':`<button class="btn sec big" ${A('go',{s:'billForm',p:{order:o.id}})}>Enter the supplier bill</button>`}</div><div class="acts"><button class="btn sec sm" ${A('root',{s:'stock'})}>See stock</button></div></div>`}};
SCREENS.supplier={sec:'orders',title:p=>SUP(p.id).name,help:['This page shows the supplier\'s contact details, what you buy from them and at what price.','Tap an item to see its stock. Tap an order to open it.','The green button starts a new order to this supplier.'],
 html(p){const s=SUP(p.id),items=S.ingredients.filter(i=>i.sup===s.id),os=S.orders.filter(o=>o.sup===s.id).sort((a,b)=>b.no-a.no);
  return `${pageHead(h(s.name),'Delivers in '+plural(s.lead,'day'),`<button class="btn" ${A('go',{s:'newOrder',p:{sup:s.id}})}>Create order</button><button class="btn sec" ${A('supForm',{id:s.id})}>Edit details</button>`)}
  <div class="card"><dl class="kv"><dt>Phone</dt><dd>${h(s.phone)||'-'}</dd><dt>Email</dt><dd>${h(s.email)||'-'}</dd><dt>TIN ${tip('tin')}</dt><dd>${h(s.tin)||'-'} <span class="muted sm">(made up)</span></dd></dl></div>
  <div class="grid g2"><div class="card pad0"><h2 style="padding:14px 16px 8px">Items and prices</h2><div class="tw">${items.length?`<table><tr><th>Item</th><th class="r">Price</th><th></th></tr>${items.map(i=>`<tr class="click" tabindex="0" ${A('go',{s:'item',p:{id:i.id}})}><td class="b">${h(i.name)}</td><td class="r">${rm(i.cost)} / ${h(i.unit)}</td><td class="chev">Open ›</td></tr>`).join('')}</table>`:empty('No items yet','Add an item and choose this supplier.',`<button class="btn" ${A('go',{s:'addItem'})}>Add item</button>`)}</div></div>
  <div class="card pad0"><h2 style="padding:14px 16px 8px">Orders</h2><div class="tw">${os.length?`<table><tr><th>Order</th><th>Sent</th><th>Status</th><th></th></tr>${os.map(o=>`<tr class="click" tabindex="0" ${A('go',{s:'order',p:{id:o.id}})}><td class="b">#${o.no}</td><td>${fDs(o.date)}</td><td>${pill(...OST[o.status])}</td><td class="chev">Open ›</td></tr>`).join('')}</table>`:empty('No orders yet','',`<button class="btn" ${A('go',{s:'newOrder',p:{sup:s.id}})}>Create the first order</button>`)}</div></div></div>`}};
ACT.supForm=p=>{const s=p.id?SUP(p.id):{name:'',phone:'',email:'',lead:1,tin:''};modal(M=>`${mHead(p.id?'Edit supplier':'Add supplier')}<div class="fgrid">${field('sf-n','Supplier name',inp('sf-n','name',M.name))}${field('sf-p','Phone',inp('sf-p','phone',M.phone,{attr:'inputmode="tel"'}))}${field('sf-e','Email',inp('sf-e','email',M.email))}${field('sf-l','Delivers in (days)',inp('sf-l','lead',M.lead,{attr:'inputmode="numeric"'}))}</div><div class="mf"><button class="btn sec" ${A('closeModal')}>Cancel</button><button class="btn" ${A('supSave')}>Save supplier</button></div>`,{id:p.id||'',name:s.name,phone:s.phone,email:s.email,lead:String(s.lead)})};
ACT.supSave=()=>{if(!M.name.trim()){toast('Supplier name is missing. Type the name, then save.');const f=document.getElementById('sf-n');if(f)f.focus();return}const lead=Math.max(1,Math.round(num(M.lead))||1);
  let id=M.id;if(id)Object.assign(SUP(id),{name:M.name.trim(),phone:M.phone,email:M.email,lead});else{id='S'+S.seq.id++;S.suppliers.push({id,name:M.name.trim(),phone:M.phone,email:M.email,lead,tin:''});IX=null}
  const isNew=!M.id;closeModal();save();if(isNew)go('supplier',{id});else render(true);toast('Supplier saved')};
SCREENS.billForm={sec:'orders',title:()=>'Enter supplier bill',help:['Copy the details from the bill (invoice) the supplier gave you.','If you came here from an order, the supplier and amount are already filled in.','Press "Save bill". You can mark it as paid later.'],
 html(p){if(!p.init){p.init=1;const o=p.order&&ordBy(p.order);Object.assign(p,{sup:o?o.sup:S.suppliers[0].id,no:'',date:today(),due:addDays(today(),14),amount:o?amt(o.lines.reduce((a,l)=>a+Math.round(l.recv*l.price),0)):'',einv:'Not received yet'})}
  const errs=p.tried?billErrs(p):[];
  return `${pageHead('Enter supplier bill',p.order?'For order #'+ordBy(p.order).no:'')}${errs.length?`<div class="errs" role="alert">${errs.map(e=>`<div class="e"><span>${e[1]}</span><button class="btn sec sm" ${A('focus',{id:e[0]})}>Fix it</button></div>`).join('')}</div>`:''}
  <div class="card"><div class="fgrid">${field('bf-s','Supplier',`<select class="inp" id="bf-s" data-m="sup">${S.suppliers.map(u=>`<option value="${u.id}" ${p.sup===u.id?'selected':''}>${h(u.name)}</option>`).join('')}</select>`)}${field('bf-n','Bill number (printed on the bill)',inp('bf-n','no',p.no,{ph:'For example: INV-1234'}))}${field('bf-a','Amount to pay (RM)',inp('bf-a','amount',p.amount,{attr:'inputmode="decimal"',ph:'0.00'}))}
   ${field('bf-d','Bill date',inp('bf-d','date',p.date,{type:'date'}))}${field('bf-u','Pay by',inp('bf-u','due',p.due,{type:'date'}))}${field('bf-e','Did the supplier send an e-invoice?',`<select class="inp" id="bf-e" data-m="einv"><option ${p.einv==='Not received yet'?'selected':''}>Not received yet</option><option ${p.einv==='Valid'?'selected':''} value="Valid">Yes, received</option></select>`,'einv')}</div></div>
  <div class="foot"><button class="btn sec" ${A('back')}>Cancel</button><div class="rt"><button class="btn big" ${A('billSave')}>Save bill</button></div></div>`}};
function billErrs(p){const e=[];if(!p.no.trim())e.push(['bf-n','Bill number is missing. Copy it from the supplier\'s bill.']);if(!(num(p.amount)>0))e.push(['bf-a','Amount is missing. Type the total on the bill, for example 245.50.']);if(!p.date)e.push(['bf-d','Bill date is missing.']);if(!p.due)e.push(['bf-u','"Pay by" date is missing.']);return e}
ACT.billSave=()=>{const p=cur().p;p.tried=1;if(billErrs(p).length){render();toast('Not saved yet. Fix the '+plural(billErrs(p).length,'point')+' in the red box first.');return}const b={id:uid('sb'),no:p.no.trim(),sup:p.sup,order:p.order||null,date:p.date,due:p.due,amount:Math.round(num(p.amount)*100),paid:false,einv:p.einv,uuid:''};S.bills.push(b);save();go('bill',{id:b.id},true);toast('Bill '+b.no+' saved')};
SCREENS.bill={sec:'orders',title:p=>{const b=S.bills.find(x=>x.id===p.id);return b?'Bill '+b.no:'Bill'},help:['This is a bill from a supplier.','Press "Mark as paid" once you have paid it.','The e-invoice line shows whether the supplier has sent you their e-invoice for this bill.'],
 html(p){const b=S.bills.find(x=>x.id===p.id);if(!b)return empty('This bill was removed','',`<button class="btn" ${A('root',{s:'orders',p:{tab:'bills'}})}>Back to bills</button>`);const o=b.order&&ordBy(b.order);
  return `${pageHead('Bill '+h(b.no),`${billPay(b)} ${einvPill(b.einv)}`,b.paid?`<button class="btn sec" ${A('billPaid',{id:b.id,v:false})}>Mark as not paid</button>`:`<button class="btn" ${A('billPaid',{id:b.id,v:true})}>Mark as paid</button>`)}
  <div class="card"><dl class="kv"><dt>Supplier</dt><dd>${h(SUP(b.sup).name)}</dd><dt>Amount</dt><dd>${rm(b.amount)}</dd><dt>Bill date</dt><dd>${fD(b.date)}</dd><dt>Pay by</dt><dd>${fD(b.due)}</dd><dt>For order</dt><dd>${o?`<button class="btn sec sm" ${A('go',{s:'order',p:{id:o.id}})}>Open order #${o.no}</button>`:'Not linked to an order'}</dd></dl></div>
  <div class="card" style="display:flex;flex-direction:column;gap:8px"><h2>Supplier's e-invoice ${tip('einv')}</h2>${b.einv==='Valid'?`<p>${pill('E-invoice received','ok')} The supplier has sent a checked e-invoice for this bill. Keep it with your records.</p><dl class="kv"><dt>Unique ID ${tip('uuid')}</dt><dd>${h(b.uuid||'(not recorded)')}</dd></dl>`
    :`<p>${pill('No e-invoice yet','warn')} Ask the supplier to send their e-invoice for this bill.</p><div><button class="btn sec" ${A('billEinv',{id:b.id})}>Mark e-invoice as received</button></div>`}<p class="muted sm">Demo only. A real system would pull this status from LHDN MyInvois.</p></div>`}};
ACT.billPaid=p=>{const b=S.bills.find(x=>x.id===p.id);b.paid=p.v;save();render(true);toast(p.v?'Bill '+b.no+' marked as paid':'Bill '+b.no+' marked as not paid',()=>{b.paid=!p.v})};
ACT.billEinv=p=>{const b=S.bills.find(x=>x.id===p.id);b.einv='Valid';b.uuid=fakeId(rng(S.seq.id++),26);save();render(true);toast('E-invoice marked as received',()=>{b.einv='Not received yet';b.uuid=''})};
