/* ---------- Waste log and Food Rescue ---------- */
SCREENS.waste={sec:'waste',title:()=>'Waste',help:['Pick the item, set the amount, tap the reason, then press "Save waste log".','Food that passes its expiry date is added to this log by itself.','"Food Rescue" lets you offer food that is close to expiry to a partner instead of binning it (demo partners only).'],
 html(p){const tab=p.tab||'log',T=today();if(p.qty==null)p.qty='1';
  const tabs=`<div class="tabs">${[['log','Waste log'],['rescue','Food Rescue']].map(([k,l])=>`<button class="tab ${tab===k?'on':''}" ${A('set',{k:'tab',v:k})}>${l}</button>`).join('')}</div>`;
  if(tab==='rescue'){const near=S.batches.filter(b=>b.qty>0.0005&&daysLeft(b)>=0&&daysLeft(b)<=S.settings.expDays+1&&!S.rescue.some(r=>r.batch===b.id&&r.status==='Offered')).sort((a,b)=>a.exp<b.exp?-1:1),ls=S.rescue.slice().reverse();
   return `${pageHead('Waste','Offer food that is close to expiry to a food charity. '+pill('Demo only: partners are made up, nothing is sent','warn'))}${tabs}
   <div class="card pad0"><h2 style="padding:14px 16px 8px">Close to expiry and still good ${tip('rescue')}</h2><div class="tw">${near.length?`<table><tr><th>Item</th><th class="r">Amount</th><th>Expires</th><th>What to do</th></tr>${near.map(b=>`<tr><td class="b">${h(ING(b.ing).name)}</td><td class="r">${qU(b.ing,b.qty)}</td><td>${pill(expTxt(b),'warn')}</td><td><button class="btn sm" ${A('rescueOffer',{b:b.id})}>Offer for rescue</button></td></tr>`).join('')}</table>`:empty('Nothing is close to expiry right now','Items show up here when they have '+plural(S.settings.expDays+1,'day')+' or less left.',`<button class="btn sec" ${A('root',{s:'stock'})}>See all stock</button>`)}</div></div>
   <div class="card pad0"><h2 style="padding:14px 16px 8px">Your rescue offers</h2><div class="tw">${ls.length?`<table><tr><th>Item</th><th class="r">Amount</th><th class="hide-s">Partner</th><th>Status</th><th>What to do</th></tr>${ls.map(r=>`<tr><td class="b">${h(ING(r.ing).name)}</td><td class="r">${qU(r.ing,r.qty)}</td><td class="hide-s">${h(r.partner)}</td><td>${pill(r.status,r.status==='Collected'?'ok':r.status==='Offered'?'info':'bad')}</td><td>${r.status==='Offered'?`<div class="row"><button class="btn sm" ${A('rescueDone',{id:r.id})}>Mark as collected</button><button class="btn red sm" ${A('rescueCancel',{id:r.id})}>Take back offer</button></div>`:'<span class="muted sm">Nothing more to do</span>'}</td></tr>`).join('')}</table>`:empty('No offers yet','Offer an item from the list above and it will show here.')}</div></div>`}
  const i=p.ing&&ix().ing[p.ing]?ING(p.ing):null,q=num(p.qty),oh=i?onHand(i.id):0;
  const why=!i?'Pick an item first.':!(q>0)?'Type an amount above 0.':q>oh+0.0005?'Only '+qU(i.id,oh)+' in stock. Lower the amount, or fix the count in Stock first.':!p.reason?'Tap a reason.':'';
  const fq=(p.q||'').trim().toLowerCase(),rows=S.waste.slice().reverse().filter(w=>!fq||ING(w.ing).name.toLowerCase().includes(fq)).slice(0,40);
  return `${pageHead('Waste','Log food that was thrown away. '+demoTag,S.role==='owner'?`<button class="btn sec" ${A('root',{s:'reports',p:{focus:'waste'}})}>${ic('chart')}See the monthly report</button>`:`<button class="btn sec" ${A('root',{s:'stock',p:{tab:'soon'}})}>${ic('clock')}See what is expiring soon</button>`)}${tabs}
  ${p.done&&S.waste.some(w=>w.id===p.done.id)?`<div class="card donebox" id="wastedone" style="padding:20px 16px"><span class="tick">${ic('check')}</span><h2>Waste logged</h2><p>${h(p.done.txt)}</p><div class="acts"><button class="btn big" id="wasteagain" ${A('set',{k:'done',v:null})}>Log another item</button><button class="btn sec big" ${A('root',{s:'home'})}>Back to Home</button></div><div class="acts"><button class="btn sec sm" ${A('wasteUndo',{id:p.done.id})}>Undo this entry</button></div></div>`:`<div class="card" id="wasteform" style="display:flex;flex-direction:column;gap:14px"><h2>Log waste</h2><div class="fgrid">
   ${field('w-ing','1. What was thrown away?',`<select class="inp" id="w-ing" data-m="ing" data-r><option value="">Pick an item</option>${ING_CATS.map(c=>`<optgroup label="${c}">${S.ingredients.filter(x=>x.cat===c).map(x=>`<option value="${x.id}" ${p.ing===x.id?'selected':''}>${h(x.name)} (${qf(onHand(x.id))} ${h(x.unit)} in stock)</option>`).join('')}</optgroup>`).join('')}</select>`)}
   <div class="field"><label for="w-qty">2. How much?${i?' ('+h(i.unit)+')':''}</label><div class="stepper"><button ${A('wasteStep',{d:-1})} aria-label="Less" ${num(p.qty)>((i&&(i.unit==='kg'||i.unit==='L'))?0.5:1)?'':'disabled'}>−</button><input class="inp" id="w-qty" inputmode="decimal" data-m="qty" data-live value="${h(p.qty)}"><button ${A('wasteStep',{d:1})} aria-label="More">+</button></div></div></div>
   <div><div class="flabel" style="margin-bottom:6px">3. Why?</div><div class="chips">${REASONS.map(r=>`<button class="chip ${p.reason===r?'on':''}" aria-pressed="${p.reason===r}" ${A('set',{k:'reason',v:r})}>${r}</button>`).join('')}</div></div>
   <div class="row"><button class="btn big" id="wastesave" ${A('wasteSave')} ${why?'disabled':''}>Save waste log</button>${why?`<span class="why">${why}</span>`:`<span class="muted sm">About ${rm(Math.round(q*i.cost))} of ${h(i.name)}</span>`}</div></div>`}
  <div class="row"><h2 class="grow">Latest entries</h2>${searchBox('q','Search the log by item',p.q)}</div>
  <div class="card pad0"><div class="tw">${rows.length?`<table><tr><th>When</th><th>Item</th><th class="r">Amount</th><th>Reason</th><th class="r hide-s">Cost</th><th></th></tr>${rows.map(w=>`<tr class="click" tabindex="0" ${A('go',{s:'wasteItem',p:{ing:w.ing}})}><td>${w.dt.slice(0,10)===T?'Today':fDs(w.dt)}, ${fT(w.dt)}</td><td class="b">${h(ING(w.ing).name)}</td><td class="r">${qU(w.ing,w.qty)}</td><td>${h(w.reason)}${w.auto?' '+pill('Added automatically','info'):''}</td><td class="r hide-s">${rm(w.cost)}</td><td class="chev">History ›</td></tr>`).join('')}</table>`
   :empty(fq?'No entry matches "'+h(fq)+'"':'No waste logged yet',fq?'':'Use the form above to log the first one.',fq?`<button class="btn sec" ${A('set',{k:'q',v:''})}>Clear search</button>`:'')}</div></div>`}};
Object.assign(ACT,{
 wasteStep:p=>{const c=cur().p,i=c.ing?ING(c.ing):null,st=i&&(i.unit==='kg'||i.unit==='L')?0.5:1;c.qty=qf(Math.max(st,(num(c.qty)||0)+p.d*st));render(true)},
 wasteSave:()=>{const c=cur().p,q=num(c.qty);if(!c.ing||!(q>0)||!c.reason)return;const w=logWaste(c.ing,q,c.reason);if(!w){toast('Nothing was logged because there is no stock of this item.');return}
   const n=ING(c.ing).name;c.ing='';c.qty='1';c.reason='';c.done={id:w.id,txt:qU(w.ing,w.qty)+' of '+n+' ('+w.reason.toLowerCase()+'), worth '+rm(w.cost)+'. Stock was reduced.'};save();render();toast(qU(w.ing,w.qty)+' of '+n+' logged as waste ('+rm(w.cost)+')',()=>undoWaste(w.id))},
 wasteUndo:p=>{const w=S.waste.find(x=>x.id===p.id);if(!w)return;const n=ING(w.ing).name;undoWaste(p.id);cur().p.done=null;save();render();toast('Entry removed. '+n+' is back in stock.')},
 rescueOffer:p=>{const b=S.batches.find(x=>x.id===p.b);if(!b)return;modal(()=>`${mHead('Offer '+h(ING(b.ing).name)+' for rescue')}<p><b>${qU(b.ing,b.qty)}</b>, ${expTxt(b).toLowerCase()==='today'?'expires today':'expires '+expTxt(b).toLowerCase()}. Who should collect it?</p>${PARTNERS.map((n,i)=>`<button class="opt" ${A('rescueDo',{b:b.id,i})}>${ic('heart')}<span><b>${n}</b><small>Made-up partner for the demo. No message is sent.</small></span></button>`).join('')}<div class="mf"><button class="btn sec" ${A('closeModal')}>Cancel</button></div>`)},
 rescueDo:p=>{const b=S.batches.find(x=>x.id===p.b);const r={id:uid('r'),batch:b.id,ing:b.ing,qty:b.qty,kg:r3(b.qty*ING(b.ing).kg),partner:PARTNERS[p.i],status:'Offered',dt:isoDT(now())};S.rescue.push(r);closeModal();save();render(true);toast('Offered to '+PARTNERS[p.i]+'. Mark it as collected when they pick it up.',()=>{S.rescue=S.rescue.filter(x=>x!==r)})},
 rescueDone:p=>{const r=S.rescue.find(x=>x.id===p.id),snap=JSON.stringify(S.batches);consume(r.ing,r.qty,r.batch);r.status='Collected';r.dt=isoDT(now());save();render(true);toast(ING(r.ing).name+' collected. It left the stock and is not counted as waste.',()=>{S.batches=JSON.parse(snap);r.status='Offered'})},
 rescueCancel:p=>{const r=S.rescue.find(x=>x.id===p.id);confirmBox({title:'Take back this offer?',body:h(ING(r.ing).name)+' will stay in your stock and the partner will no longer be expected to collect it.',ok:'Yes, take it back',no:'No, keep the offer',danger:true,yes:()=>{r.status='Taken back';save();render(true);toast('Offer taken back',()=>{r.status='Offered'})}})}
});
SCREENS.wasteItem={sec:'waste',title:p=>'Waste history: '+ING(p.ing).name,help:['Every time this item was thrown away is listed here, newest first.','Look at the reasons. If most are "Expired", try ordering less or more often.','"Open this item in Stock" shows what is on the shelf now.'],
 html(p){const i=ING(p.ing),ws=S.waste.filter(w=>w.ing===p.ing).reverse(),c=ws.reduce((a,w)=>a+w.cost,0),k=r3(ws.reduce((a,w)=>a+w.kg,0));
  return `${pageHead('Waste history: '+h(i.name),plural(ws.length,'entry','entries')+' in the last 2 months · '+qf(k)+' kg · '+rm(c)+' '+demoTag,`<button class="btn" ${A('go',{s:'item',p:{id:i.id}})}>Open this item in Stock</button>`)}
  <div class="card pad0"><div class="tw">${ws.length?`<table><tr><th>When</th><th class="r">Amount</th><th>Reason</th><th class="r">Cost</th><th>What to do</th></tr>${ws.map(w=>`<tr><td>${fDT(w.dt)}</td><td class="r">${qU(w.ing,w.qty)}</td><td>${h(w.reason)}${w.auto?' '+pill('Added automatically','info'):''}</td><td class="r">${rm(w.cost)}</td><td>${w.dt.slice(0,10)===today()?`<button class="btn red sm" ${A('wasteRemove',{id:w.id})}>Remove entry</button>`:'<span class="muted sm">Older entries are locked</span>'}</td></tr>`).join('')}</table>`:empty('No waste logged for this item','That is a good thing.',`<button class="btn sec" ${A('root',{s:'waste'})}>Back to the waste log</button>`)}</div></div>`}};
ACT.wasteRemove=p=>{const w=S.waste.find(x=>x.id===p.id);confirmBox({title:'Remove this waste entry?',body:qU(w.ing,w.qty)+' of '+h(ING(w.ing).name)+' will go back into stock, as if it was never thrown away.',ok:'Yes, remove the entry',no:'No, keep it',danger:true,yes:()=>{undoWaste(w.id);save();render(true);toast('Entry removed. The stock is back.')}})};

/* ---------- Reports ---------- */
SCREENS.reports={sec:'reports',title:()=>'Reports',help:['Pick a month at the top. Every number below is for that month.','Tap a number or a row to see what is behind it.','"Copy as spreadsheet" gives you the figures to paste into Excel or Google Sheets.'],
 html(p){const T=today(),m=p.m||T.slice(0,7),ms=[0,-1,-2].map(k=>addMonth(T.slice(0,7),k)),st=monthStats(m),wk=weeklyWaste(9);
  TEXTS.wasteCsv=()=>toCSV([['Date','Time','Item','Amount','Unit','Reason','Added automatically','Weight (kg)','Cost (RM)'],...st.waste.map(w=>[w.dt.slice(0,10),w.dt.slice(11),ING(w.ing).name,w.qty,ING(w.ing).unit,w.reason,w.auto?'Yes':'No',w.kg,amt(w.cost)])]);TEXTS.wasteCsv.file='goodbite-waste-'+m+'.csv';
  TEXTS.salesCsv=()=>toCSV([['Date','Bills','Sales incl. tax (RM)','Sales before tax and service charge (RM)','Service charge (RM)','SST (RM)','Ingredient cost (RM)'],...st.daily.map(d=>{const x=S.days[d.d]||{bills:0,total:0,sub:0,sc:0,sst:0,cogs:0};return[d.d,x.bills,amt(x.total),amt(x.sub),amt(x.sc),amt(x.sst),amt(x.cogs)]})]);TEXTS.salesCsv.file='goodbite-sales-'+m+'.csv';
  const maxTop=Math.max(1,...st.top.slice(0,8).map(x=>x.cost)),maxR=Math.max(1,...st.reasons.map(x=>x.cost));
  if(p.focus){const f=p.focus;p.focus='';setTimeout(()=>{const e=document.getElementById('rep-'+f);if(e)e.scrollIntoView({block:'start'})},0)}
  return `${pageHead('Reports','How the outlet is doing. '+pill('Demo data: every figure here is made up','warn'),`<button class="btn sec" ${A('showText',{t:'Waste log for '+fM(m),k:'wasteCsv'})}>${ic('copy')}Copy waste log as spreadsheet</button><button class="btn sec" ${A('showText',{t:'Daily sales for '+fM(m),k:'salesCsv'})}>${ic('copy')}Copy daily sales as spreadsheet</button>`)}
  <div class="tabs">${ms.map(x=>`<button class="tab ${m===x?'on':''}" ${A('set',{k:'m',v:x})}>${fM(x)}</button>`).join('')}</div>
  <div class="grid g4">
   <button class="kpi" ${A('go',{s:'repDays',p:{m}})}><span class="l">Sales (with tax)</span><span class="v">${rm(st.sales)}</span><span class="s lnk">${plural(st.bills,'bill')} · see each day ›</span></button>
   <button class="kpi" ${A('foodCost',{m})}><span class="l">Food cost ${''}</span><span class="v">${st.fc.toFixed(1)}%</span><span class="s lnk">${rm(st.cogs)} of ingredients · how? ›</span></button>
   <button class="kpi" ${A('go',{s:'repWaste',p:{m}})}><span class="l">Waste</span><span class="v">${rm(st.wRM)}</span><span class="s lnk">${qf(st.wKg)} kg · see every entry ›</span></button>
   <button class="kpi" ${A('root',{s:'waste',p:{tab:'rescue'}})}><span class="l">Rescued instead of binned</span><span class="v">${qf(st.resc)} kg</span><span class="s lnk">Open Food Rescue ›</span></button></div>
  <div class="card" id="rep-sales"><h2>Sales per day, ${fM(m)}</h2>${st.daily.length?barChart(st.daily.map(d=>({l:String(+d.d.slice(8)),v:d.v/100,t:fDs(d.d)+': '+rm(d.v)+' from '+plural(d.b,'bill')})),{fmt:v=>'RM '+(v>=1000?(v/1000)+'k':v),label:'Sales per day in '+fM(m)}):'<p class="muted">No sales yet this month.</p>'}<p class="muted sm">Day of the month along the bottom. Hover or tap a bar to see the amount.</p></div>
  <div class="grid g2" id="rep-waste"><div class="card"><h2>Waste per week, in kg</h2>${barChart(wk.map(w=>({l:fDs(w.a),v:w.kg,t:'Week of '+fDs(w.a)+': '+qf(w.kg)+' kg'})),{fmt:v=>v+' kg',h:170,label:'Waste per week in kilograms'})}</div>
   <div class="card"><h2>Waste per week, in RM</h2>${barChart(wk.map(w=>({l:fDs(w.a),v:w.cost/100,t:'Week of '+fDs(w.a)+': '+rm(w.cost)})),{fmt:v=>'RM '+v,h:170,label:'Waste per week in ringgit'})}</div></div>
  <div class="grid g2"><div class="card pad0"><h2 style="padding:14px 16px 8px">Most wasted items, ${fM(m)}</h2><div class="tw">${st.top.length?`<table><tr><th>Item</th><th class="r">Thrown away</th><th class="r">Cost</th><th></th></tr>${st.top.slice(0,8).map(x=>`<tr class="click" tabindex="0" ${A('go',{s:'wasteItem',p:{ing:x.ing}})}><td><b>${h(ING(x.ing).name)}</b><div class="hbar" style="grid-template-columns:1fr"><i style="width:${Math.max(3,x.cost/maxTop*100)}%"></i></div></td><td class="r">${qU(x.ing,x.qty)}</td><td class="r">${rm(x.cost)}</td><td class="chev">History ›</td></tr>`).join('')}</table>`:empty('No waste logged this month','')}</div></div>
   <div class="card" style="display:flex;flex-direction:column;gap:10px"><h2>Why food was wasted</h2>${st.reasons.length?st.reasons.map(r=>`<div class="hbar"><span>${h(r.reason)}</span><i style="width:${Math.max(2,r.cost/maxR*100)}%"></i><b class="num">${rm(r.cost)}</b></div>`).join(''):'<p class="muted">No waste logged this month.</p>'}
    <div id="rep-cost" style="margin-top:auto;padding-top:10px;border-top:1px solid var(--line)"><div class="tot"><span>Waste compared with sales before tax</span><b>${st.wp.toFixed(1)}%</b></div><div class="tot"><span>Food cost ${tip('fc')}</span><b>${st.fc.toFixed(1)}%</b></div></div></div></div>`}};
ACT.foodCost=p=>{const st=monthStats(p.m);modal(()=>`${mHead('How food cost is worked out')}<p>Food cost % = cost of the ingredients used in what you sold, divided by sales before tax and service charge.</p><dl class="kv"><dt>Ingredients used</dt><dd>${rm(st.cogs)}</dd><dt>Sales before tax</dt><dd>${rm(st.net)}</dd><dt>Food cost</dt><dd>${st.fc.toFixed(1)}%</dd><dt>Waste on top of that</dt><dd>${rm(st.wRM)} (${st.wp.toFixed(1)}% of sales)</dd></dl><p class="muted sm">The app adds up each recipe every time an item is sold. All prices here are demo prices.</p><div class="mf"><button class="btn" ${A('closeModal')}>Got it</button></div>`)};
SCREENS.repDays={sec:'reports',title:p=>'Sales by day, '+fM(p.m),help:['One row for each day of the month.','"Ingredient cost" is what the food sold that day cost you to make.','Go back to Reports to change the month.'],
 html(p){const st=monthStats(p.m);return `${pageHead('Sales by day, '+fM(p.m),demoTag,`<button class="btn sec" ${A('showText',{t:'Daily sales for '+fM(p.m),k:'salesCsv'})}>${ic('copy')}Copy as spreadsheet</button>`)}
  <div class="card pad0"><div class="tw"><table><tr><th>Day</th><th class="r">Bills</th><th class="r">Sales (with tax)</th><th class="r hide-s">Before tax</th><th class="r hide-s">Ingredient cost</th></tr>${st.daily.slice().reverse().map(d=>{const x=S.days[d.d]||{bills:0,total:0,sub:0,cogs:0};return`<tr><td>${fD(d.d)}${d.d===today()?' '+pill('Today','info'):''}</td><td class="r">${x.bills}</td><td class="r b">${rm(x.total)}</td><td class="r hide-s">${rm(x.sub)}</td><td class="r hide-s">${rm(x.cogs)}</td></tr>`}).join('')}<tr><td class="b">Month so far</td><td class="r b">${st.bills}</td><td class="r b">${rm(st.sales)}</td><td class="r b hide-s">${rm(st.net)}</td><td class="r b hide-s">${rm(st.cogs)}</td></tr></table></div></div>`}};
SCREENS.repWaste={sec:'reports',title:p=>'Waste entries, '+fM(p.m),help:['Every waste entry of the month, newest first.','Tap a row to see the full waste history of that item.','"Copy as spreadsheet" gives you the list for Excel.'],
 html(p){const st=monthStats(p.m),ws=st.waste.slice().reverse();return `${pageHead('Waste entries, '+fM(p.m),qf(st.wKg)+' kg · '+rm(st.wRM)+' '+demoTag,`<button class="btn sec" ${A('showText',{t:'Waste log for '+fM(p.m),k:'wasteCsv'})}>${ic('copy')}Copy as spreadsheet</button>`)}
  <div class="card pad0"><div class="tw">${ws.length?`<table><tr><th>When</th><th>Item</th><th class="r">Amount</th><th>Reason</th><th class="r hide-s">Weight</th><th class="r">Cost</th><th></th></tr>${ws.map(w=>`<tr class="click" tabindex="0" ${A('go',{s:'wasteItem',p:{ing:w.ing}})}><td>${fDs(w.dt)}</td><td class="b">${h(ING(w.ing).name)}</td><td class="r">${qU(w.ing,w.qty)}</td><td>${h(w.reason)}</td><td class="r hide-s">${qf(w.kg)} kg</td><td class="r">${rm(w.cost)}</td><td class="chev">History ›</td></tr>`).join('')}</table>`:empty('No waste logged in '+fM(p.m),'',`<button class="btn sec" ${A('root',{s:'waste'})}>Open the waste log</button>`)}</div></div>`}};
